import { AssetType, AssetSector } from "./types";

export const APPROVED_ASSETS: Record<string, {
    symbol: string,
    name: string,
    description: string,
    whyThis: string,
    whyNot: string,
    price: number,
    type: AssetType,
    sector: AssetSector,
    yield: number,
    expenseRatio: number,
    isPro?: boolean // True for Pro-only InvestPedia entries
}> = {
    // ===== THE TITANS (Free: VOO, VTI) =====
    "VTI": {
        symbol: "VTI",
        name: "Vanguard Total Stock Market",
        description: "The 'Everything' Bagel. You own basically every public company in the US.",
        whyThis: "Ultimate diversification. If the US economy grows, you grow. You don't have to be right about any single company.",
        whyNot: "If you want to 'beat the market' or only want tech, this is too slow and broad for you.",
        price: 245.50,
        type: "ETF",
        sector: "Broad",
        yield: 1.5,
        expenseRatio: 0.03
    },
    "VOO": {
        symbol: "VOO",
        name: "Vanguard S&P 500 ETF",
        description: "The 'Titan' Fund. The 500 largest US companies.",
        whyThis: "The gold standard of investing. Features the biggest, most successful companies in history.",
        whyNot: "Misses out on 'small' high-growth companies. It's safe, but not spicy.",
        price: 480.20,
        type: "ETF",
        sector: "Broad",
        yield: 1.4,
        expenseRatio: 0.03
    },
    "BRK.B": {
        symbol: "BRK.B",
        name: "Berkshire Hathaway B",
        description: "Warren Buffett's Empire. A conglomerate of conglomerates.",
        whyThis: "Own a piece of the best capital allocator in history. Insurance, railroads, Apple, Coca-Cola.",
        whyNot: "Buffett is 90+. Succession risk is real.",
        price: 415.20,
        type: "Stock",
        sector: "Financial",
        yield: 0,
        expenseRatio: 0,
        isPro: true
    },

    // ===== GLOBAL REACH (Free: VXUS) =====
    "VXUS": {
        symbol: "VXUS",
        name: "Vanguard Total International",
        description: "The 'World' View. Companies outside the US (Samsung, Toyota, Nestle).",
        whyThis: "The US doesn't always win. Having international exposure protects you if the dollar or US market takes a decade-long nap.",
        whyNot: "International markets often grow slower than US tech. It's for safety, not for flexing.",
        price: 62.20,
        type: "ETF",
        sector: "Broad",
        yield: 3.2,
        expenseRatio: 0.08
    },
    "ASML": {
        symbol: "ASML",
        name: "ASML Holding",
        description: "The Machine that Makes Machines. They own the monopoly on high-end chip lithography.",
        whyThis: "If you want chips, you need ASML. They are the ultimate bottleneck in the tech world.",
        whyNot: "Very expensive and sensitive to trade wars with China.",
        price: 920.50,
        type: "Stock",
        sector: "Tech",
        yield: 0.7,
        expenseRatio: 0,
        isPro: true
    },

    // ===== THE AI FUTURE (Free: XLK, AAPL, QQQ) =====
    "QQQ": {
        symbol: "QQQ",
        name: "Invesco QQQ (NASDAQ 100)",
        description: "The 'Tech Titans' Fund. Top 100 NASDAQ stocks, heavy on Apple, Microsoft, Amazon, Nvidia.",
        whyThis: "Pure tech and growth exposure. When tech runs hot, QQQ runs hotter.",
        whyNot: "Zero diversification outside tech/growth. When bubbles pop, this drops 30%+ fast.",
        price: 485.30,
        type: "ETF",
        sector: "Tech",
        yield: 0.5,
        expenseRatio: 0.20
    },
    "XLK": {
        symbol: "XLK",
        name: "Technology Select Sector",
        description: "The 'Future' Play. Microsoft, Apple, Nvidia, etc.",
        whyThis: "Concentrated power. If tech runs the world, this fund runs your portfolio.",
        whyNot: "Very high volatility. When tech bubbles pop, this drops harder than the general market.",
        price: 210.30,
        type: "ETF",
        sector: "Tech",
        yield: 0.7,
        expenseRatio: 0.10
    },
    "AAPL": {
        symbol: "AAPL",
        name: "Apple Inc.",
        description: "The iPhone empire. Hardware, software, services.",
        whyThis: "The most valuable company in the world with incredible brand loyalty and cash flow.",
        whyNot: "Dependent on iPhone sales. If innovation slows, so does growth.",
        price: 195.20,
        type: "Stock",
        sector: "Tech",
        yield: 0.5,
        expenseRatio: 0
    },
    "NVDA": {
        symbol: "NVDA",
        name: "NVIDIA Corporation",
        description: "The AI King. GPUs powering every data center.",
        whyThis: "Dominates AI chips. If AI is the future, NVIDIA is building it.",
        whyNot: "Priced for perfection. Any slowdown and it crashes.",
        price: 485.90,
        type: "Stock",
        sector: "Tech",
        yield: 0.03,
        expenseRatio: 0,
        isPro: true
    },
    "MSFT": {
        symbol: "MSFT",
        name: "Microsoft Corporation",
        description: "Cloud, Office, Windows, AI partnerships.",
        whyThis: "Enterprise software king. Azure is crushing it and they own a piece of OpenAI.",
        whyNot: "Antitrust concerns are always looming.",
        price: 410.30,
        type: "Stock",
        sector: "Tech",
        yield: 0.7,
        expenseRatio: 0,
        isPro: true
    },
    "AMZN": {
        symbol: "AMZN",
        name: "Amazon.com, Inc.",
        description: "The Everything Store & Cloud King (AWS).",
        whyThis: "Unstoppable scale and constant innovation. They own the internet's backbone.",
        whyNot: "Regulatory heat and thin retail margins.",
        price: 185.20,
        type: "Stock",
        sector: "Discretionary",
        yield: 0,
        expenseRatio: 0,
        isPro: true
    },
    "GOOGL": {
        symbol: "GOOGL",
        name: "Alphabet Inc.",
        description: "Search, YouTube, and AI labs. The world's entry point to information.",
        whyThis: "Dominant ads business and massive data advantages for AI training.",
        whyNot: "Legal challenges and competition in AI search.",
        price: 155.40,
        type: "Stock",
        sector: "Tech",
        yield: 0,
        expenseRatio: 0,
        isPro: true
    },

    // ===== ECONOMIC PULSE (Free: XLF, XLE) =====
    "XLF": {
        symbol: "XLF",
        name: "Financial Select Sector",
        description: "The 'Vault'. Big banks, insurance, brokers.",
        whyThis: "Interest rates. When rates go up, banks often make more money. Solid dividends.",
        whyNot: "If the housing market or credit market breaks, these companies go first. See 2008.",
        price: 42.10,
        type: "ETF",
        sector: "Financial",
        yield: 1.8,
        expenseRatio: 0.10
    },
    "XLE": {
        symbol: "XLE",
        name: "Energy Select Sector",
        description: "The 'Fuel'. Oil, Gas, Energy titans.",
        whyThis: "Inflation hedge. If gas prices go up, your portfolio feels a bit better.",
        whyNot: "Extremely tied to oil prices and geopolitics. Very volatile and 'old world'.",
        price: 88.90,
        type: "ETF",
        sector: "Energy",
        yield: 3.5,
        expenseRatio: 0.10
    },
    "XLI": {
        symbol: "XLI",
        name: "Industrial Select Sector",
        description: "Planes, Trains, and Heavy Machines (GE, Honeywell, UPS).",
        whyThis: "Betting on the physical world. If the economy builds stuff, XLI wins.",
        whyNot: "Cyclical. Hits hard when the economy slows down.",
        price: 122.30,
        type: "ETF",
        sector: "Industrial",
        yield: 1.5,
        expenseRatio: 0.10,
        isPro: true
    },
    "JPM": {
        symbol: "JPM",
        name: "JPMorgan Chase & Co.",
        description: "The biggest US bank. Investment banking + consumer banking.",
        whyThis: "Jamie Dimon's empire. Best-in-class risk management.",
        whyNot: "Banks are leveraged. When things go wrong, they go very wrong.",
        price: 198.50,
        type: "Stock",
        sector: "Financial",
        yield: 2.2,
        expenseRatio: 0,
        isPro: true
    },
    "XOM": {
        symbol: "XOM",
        name: "Exxon Mobil Corp.",
        description: "The Energy Giant. Oil and Gas at massive scale.",
        whyThis: "Inflation hedge and huge dividends. They make money when pump prices are high.",
        whyNot: "The world is moving to green energy. Is this a dinosaur or a cash cow?",
        price: 118.20,
        type: "Stock",
        sector: "Energy",
        yield: 3.2,
        expenseRatio: 0,
        isPro: true
    },
    "TSLA": {
        symbol: "TSLA",
        name: "Tesla, Inc.",
        description: "EVs, robots, energy storage, and Elon's vision.",
        whyThis: "First mover in EVs. Software and brand create insane margins.",
        whyNot: "Priced like a tech company, operates like a car company. Drama included free.",
        price: 245.60,
        type: "Stock",
        sector: "Discretionary",
        yield: 0,
        expenseRatio: 0,
        isPro: true
    },

    // ===== THE ESSENTIALS (Free: XLP, XLV) =====
    "XLP": {
        symbol: "XLP",
        name: "Consumer Staples Select",
        description: "The 'Essentials'. Food, drinks, toilet paper.",
        whyThis: "Recession-proof. People don't stop buying groceries when the stock market crashes.",
        whyNot: "Boring. Don't expect these stocks to double overnight. It's slow and steady.",
        price: 76.40,
        type: "ETF",
        sector: "Staples",
        yield: 2.5,
        expenseRatio: 0.10
    },
    "XLV": {
        symbol: "XLV",
        name: "Health Care Select Sector",
        description: "The 'Lifeline' Play. Hospitals, Pharma, Biotech.",
        whyThis: "Defensive growth. People need medicine whether the economy is good or bad.",
        whyNot: "Heavily regulated. One government policy change can tank the whole sector.",
        price: 145.80,
        type: "ETF",
        sector: "Healthcare",
        yield: 1.6,
        expenseRatio: 0.10
    },
    "KO": {
        symbol: "KO",
        name: "The Coca-Cola Company",
        description: "The world's most famous beverage brand.",
        whyThis: "Warren Buffett's favorite. Global distribution, insane brand power.",
        whyNot: "Sugar is out of fashion. Growth is slow.",
        price: 62.30,
        type: "Stock",
        sector: "Staples",
        yield: 3.0,
        expenseRatio: 0,
        isPro: true
    },
    "PG": {
        symbol: "PG",
        name: "Procter & Gamble",
        description: "Tide, Pampers, Gillette. Essential products for every home.",
        whyThis: "The ultimate defensive stock. People still wash clothes in a recession.",
        whyNot: "Very slow growth. It's a safety play, not a wealth builder.",
        price: 165.70,
        type: "Stock",
        sector: "Staples",
        yield: 2.3,
        expenseRatio: 0,
        isPro: true
    },
    "COST": {
        symbol: "COST",
        name: "Costco Wholesale",
        description: "Bulk buying and memberships. High loyalty, high efficiency.",
        whyThis: "Memberships provide stable cash flow. People love the hot dog and the savings.",
        whyNot: "Trading at a massive premium. You're paying a lot for that quality.",
        price: 725.10,
        type: "Stock",
        sector: "Staples",
        yield: 0.6,
        expenseRatio: 0,
        isPro: true
    },
    "JNJ": {
        symbol: "JNJ",
        name: "Johnson & Johnson",
        description: "Medical devices, pharma, and consumer health.",
        whyThis: "A healthcare conglomerate with a bulletproof balance sheet.",
        whyNot: "Constant lawsuits (talc, opioids) eat into the profits.",
        price: 158.30,
        type: "Stock",
        sector: "Healthcare",
        yield: 3.0,
        expenseRatio: 0,
        isPro: true
    },

    // ===== YIELD & ASSETS (Free: DGRO, VNQ) =====
    "SCHD": {
        symbol: "SCHD",
        name: "Schwab US Dividend Equity",
        description: "High-quality dividend payers with growth potential.",
        whyThis: "Best of both worlds: dividends + quality. Compound interest machine.",
        whyNot: "Lower yield than pure income funds. You're betting on growth too.",
        price: 78.40,
        type: "ETF",
        sector: "Dividend",
        yield: 3.5,
        expenseRatio: 0.06,
        isPro: true
    },
    "VNQ": {
        symbol: "VNQ",
        name: "Vanguard Real Estate ETF",
        description: "Own real estate without being a landlord.",
        whyThis: "Inflation hedge. Real assets that generate rental income.",
        whyNot: "Interest rates crush REITs. When rates rise, VNQ falls.",
        price: 86.40,
        type: "ETF",
        sector: "Real Estate",
        yield: 4.2,
        expenseRatio: 0.12
    },
    "XLRE": {
        symbol: "XLRE",
        name: "Real Estate Select Sector",
        description: "The 'Landlord' Fund. Owns malls, data centers, and apartments.",
        whyThis: "High dividends and a hedge against inflation.",
        whyNot: "Interest rates are the enemy of real estate. High rates = low property values.",
        price: 38.40,
        type: "ETF",
        sector: "Real Estate",
        yield: 3.5,
        expenseRatio: 0.10,
        isPro: true
    },
    "DGRO": {
        symbol: "DGRO",
        name: "iShares Core Dividend Growth",
        description: "Companies that keep raising their dividends year after year.",
        whyThis: "Compound interest in action. Quality companies that reward shareholders.",
        whyNot: "Yield is lower than 'high yield' funds. You're waiting for the growth.",
        price: 58.20,
        type: "ETF",
        sector: "Dividend",
        yield: 2.2,
        expenseRatio: 0.08
    },

    // ===== THE BUNKER (Free: BND, SHV) =====
    "BND": {
        symbol: "BND",
        name: "Vanguard Total Bond Market",
        description: "The 'Safety Net'. IOUs from governments and stable companies.",
        whyThis: "Ballast. When stocks crash 30%, bonds usually hold steady or go up. It keeps you from panicking.",
        whyNot: "Returns are low. You're preserving wealth, not building it.",
        price: 72.80,
        type: "Fund",
        sector: "Bonds",
        yield: 4.5,
        expenseRatio: 0.03
    },
    "GLD": {
        symbol: "GLD",
        name: "SPDR Gold Shares",
        description: "Pure gold exposure without the physical storage.",
        whyThis: "The OG hedge. Chaos hedge, inflation hedge, everything-is-breaking hedge.",
        whyNot: "No yield. Gold doesn't pay dividends. It just sits there being shiny.",
        price: 218.40,
        type: "ETF",
        sector: "Commodities",
        yield: 0,
        expenseRatio: 0.40,
        isPro: true
    },
    "TLT": {
        symbol: "TLT",
        name: "20+ Year Treasury Bond ETF",
        description: "Long-term IOUs from the US Government.",
        whyThis: "The ultimate insurance policy. When stocks crash, TLT often skyrockets.",
        whyNot: "Highly sensitive to interest rates. If rates stay high, TLT stays low.",
        price: 92.50,
        type: "ETF",
        sector: "Bonds",
        yield: 3.8,
        expenseRatio: 0.15,
        isPro: true
    },
    "SHV": {
        symbol: "SHV",
        name: "Short Treasury Bond ETF",
        description: "Extra-safe money market alternative.",
        whyThis: "Basically cash that pays interest. No volatility, pure safety.",
        whyNot: "Literal inflation victim. You won't get rich here.",
        price: 110.10,
        type: "ETF",
        sector: "Bonds",
        yield: 5.2,
        expenseRatio: 0.15
    },
    // ===== STRATEGIC INCOME (Advanced Harvesting Phase) =====
    "JPI": {
        symbol: "JPI",
        name: "Juno Premium Income",
        description: "The 'Cash Machine'. Sells options to generate high monthly yield.",
        whyThis: "Pay your monthly bills with dividends. Ideal for the harvesting phase.",
        whyNot: "Capped upside. In a bull market, JPI stays flat while others double. You are trading your future growth for cash today.",
        price: 54.20,
        type: "ETF",
        sector: "Strategic Income",
        yield: 8.5,
        expenseRatio: 0.35,
        isPro: true
    },
    "RTY": {
        symbol: "RTY",
        name: "Realty Income Titan",
        description: "The 'Monthly Landlord'. Owns thousands of commercial properties.",
        whyThis: "Predictable, monthly cash flow. Like being a landlord without the plumber phone calls.",
        whyNot: "Highly sensitive to interest rates and real estate crashes. If malls die, RTY dies.",
        price: 58.40,
        type: "REIT",
        sector: "Strategic Income",
        yield: 5.8,
        expenseRatio: 0,
        isPro: true
    },
    "HYB": {
        symbol: "HYB",
        name: "High Yield Burner",
        description: "The 'Danger' Bond. Loans to companies with bad credit.",
        whyThis: "Maximum yield. When times are good, you make a killing on interest.",
        whyNot: "If a recession hits, these companies go bankrupt first. The principal can drop 30% in a week. Extreme risk.",
        price: 88.50,
        type: "Fund",
        sector: "Strategic Income",
        yield: 7.2,
        expenseRatio: 0.50,
        isPro: true
    },

    // ===== UTILITY =====
    "CASH": {
        symbol: "CASH",
        name: "Settled Cash",
        description: "Your 'Dry Powder'. Dollars waiting to be used.",
        whyThis: "No risk, total liquidity. It's the stable foundation of your empire.",
        whyNot: "Inflation. Cash sitting idle is slowly losing value every year.",
        price: 1.00,
        type: "Other",
        sector: "Cash",
        yield: 4.0,
        expenseRatio: 0
    }
};

