name = "northern-step-studio-website"
main = "src/worker/index.ts"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "northern-step-studio-website"
database_id = "73c9a931-0d76-4ecc-b32d-c1293ce5579c"
