ALTER TABLE apps ADD COLUMN tagline TEXT;
ALTER TABLE apps ADD COLUMN full_description TEXT;
ALTER TABLE apps ADD COLUMN status_label TEXT;
ALTER TABLE apps ADD COLUMN target_date TEXT;
ALTER TABLE apps ADD COLUMN tech_stack TEXT;
ALTER TABLE apps ADD COLUMN progress TEXT;

INSERT OR IGNORE INTO apps (
  uuid,
  name,
  slug,
  tagline,
  description,
  full_description,
  category,
  status,
  status_label,
  target_date,
  tech_stack,
  progress,
  logo,
  screenshots,
  cta_url,
  video_url,
  features,
  platform,
  visibility,
  progress_percent,
  monetization
) VALUES
(
  lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || '4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
  'ProvLy',
  'provly',
  'Local-First Home Inventory Vault',
  'ProvLy is a privacy-first home inventory vault that helps households document belongings, attach receipts and warranties, build organized insurance claim packs, and stay ahead of maintenance reminders.',
  'ProvLy is a privacy-first home inventory vault designed for insurance readiness and long-term household care. It keeps inventory records, receipts, warranties, exports, and reminders in one place without turning the product into a bloated enterprise platform.',
  'HOME',
  'COMING_SOON',
  'Coming Soon',
  'Q4 2026',
  '["React Native","SQLite","Claim Pack Export"]',
  '[{"text":"Homes, rooms, and item capture flow","completed":true},{"text":"Receipt, warranty, and document attachment flow","completed":true},{"text":"Claim Pack export for insurance-ready reports","completed":true},{"text":"Maintenance reminder engine","completed":true},{"text":"Opt-in AI receipt parsing and scan assist","completed":false},{"text":"Subscription billing and production export delivery","completed":false}]',
  '/brand/provly-logo.png',
  '[]',
  'https://drive.google.com/uc?export=download&id=1-HgGFNgREMH3v_s3SvygVBBaLD4lXtCI',
  NULL,
  '["Claim Pack Export: Generate PDF, CSV, and ZIP exports with receipts, photos, and item records for insurance claims","Maintenance Reminders: Keep appliances and equipment on predictable care schedules instead of relying on memory","AI Assist: Use optional assisted parsing for receipts and faster household inventory setup"]',
  'mobile',
  'published',
  76,
  'Free'
),
(
  lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || '4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
  'NexusBuild',
  'nexusbuild',
  'AI-Powered PC Build Companion',
  'NexusBuild helps PC builders compare parts, validate compatibility, manage builds, and use AI-assisted recommendations without losing visibility into the real hardware tradeoffs.',
  'NexusBuild is a full-stack PC building companion spanning mobile, web, backend services, and deal tracking workflows. It is built for enthusiasts who want compatibility confidence, cleaner build planning, and smarter part selection support.',
  'AI TOOL',
  'COMING_SOON',
  'Coming Soon',
  'Q3 2026',
  '["React Native","React","PostgreSQL"]',
  '[{"text":"Mobile app, web app, and backend foundation","completed":true},{"text":"Compatibility engine and build management","completed":true},{"text":"AI recommendation workflow","completed":true},{"text":"Price tracking and deal alert surfaces","completed":true},{"text":"Subscription and entitlement rollout","completed":false},{"text":"Production affiliate and notification wiring","completed":false}]',
  '/brand/nexusbuild-logo.png',
  '[]',
  'https://drive.google.com/uc?export=download&id=1xkZFmxgmZisxI3XttBL9Q3fzAK4obqe0',
  NULL,
  '["AI Recommendations: Generate smarter build ideas around budget, performance, and intent instead of picking parts blind","Compatibility Engine: Check sockets, power, fit, and supporting constraints before a build turns into a mismatch","Build and Deal Tracking: Save builds, compare options, and watch pricing without leaving the product"]',
  'mobile',
  'published',
  84,
  'Free'
),
(
  lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || '4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
  'NooBS Investing',
  'noobs-investing',
  'Beginner-Friendly Investing Companion',
  'NooBS Investing teaches core market concepts through guided lessons, behavioral simulations, mini-games, and visual progress systems designed for first-time investors.',
  'NooBS Investing is a mobile-first learning companion built to make intimidating finance concepts easier to absorb. It blends structured lessons, interactive practice, and premium visual feedback into a product that feels approachable instead of academic.',
  'FINANCE',
  'COMING_SOON',
  'Coming Soon',
  'Q2 2026',
  '["React Native","Interactive Lessons","Gamified Learning"]',
  '[{"text":"Language-first onboarding and lesson flow","completed":true},{"text":"Core mini-games and learning modules","completed":true},{"text":"Portfolio analytics and progress systems","completed":true},{"text":"Premium paywall and entitlement scaffold","completed":true},{"text":"Production billing and legal link cleanup","completed":false},{"text":"Launch QA across translations and settings","completed":false}]',
  '/brand/noobs-investing-logo.png',
  '[]',
  'https://drive.google.com/uc?export=download&id=1Sf7j0viRyWQGPPmXE-rww5SI2l4Qmsd1',
  NULL,
  '["Structured Lessons: Learn core investing ideas through guided, beginner-friendly flows instead of disconnected articles","Interactive Simulations: Practice concepts with behavior-driven mini-games and market scenarios","Visual Progress Systems: Track understanding and momentum with a clearer, more motivating feedback loop"]',
  'mobile',
  'published',
  72,
  'Free'
),
(
  lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || '4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
  'NeuroMoves',
  'neuromoves',
  'Guided OT Companion for Children',
  'NeuroMoves is a guided occupational therapy companion for young children, combining errorless-learning activities, routines, parent tools, and progress tracking in a friendly mobile experience.',
  'NeuroMoves is designed around structured movement, communication, and routine-building activities for children. It combines approachable visuals, guided prompts, parent-facing tools, and therapy-friendly reporting to keep the app useful outside of a single session.',
  'EDUCATION',
  'COMING_SOON',
  'Coming Soon',
  'Q2 2026',
  '["React Native","Therapy Activities","Parent Profiles"]',
  '[{"text":"Core OT activity flows, auth, and onboarding","completed":true},{"text":"Child profile management and routine setup","completed":true},{"text":"Text-to-speech guidance and haptic feedback","completed":true},{"text":"Progress reports, journal, and rewards systems","completed":true},{"text":"Production billing and auth hardening","completed":false},{"text":"Therapy content QA and launch cleanup","completed":false}]',
  '/brand/neuromoves-logo.png',
  '[]',
  'https://drive.google.com/uc?export=download&id=11eXBZ8C9_JtcDDIxexRSBRyjAVFYXvrK',
  NULL,
  '["Errorless Learning Activities: Guide children through structured tasks with gentle feedback instead of failure-heavy loops","Parent and Therapist Tools: Manage child profiles, routines, journals, and progress reporting in one place","Engagement Systems: Use rewards, avatar progression, and guided prompts to keep routines consistent"]',
  'mobile',
  'published',
  63,
  'Free'
),
(
  lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || '4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))),
  'PasoScore',
  'pasoscore',
  'Deterministic Credit Builder Companion',
  'PasoScore is a mobile-first credit guidance app that walks users through month-by-month improvement steps with deterministic decision paths, multilingual support, and zero credit-bureau access.',
  'PasoScore focuses on practical credit-building guidance without turning the product into a high-risk prediction system. It stays deterministic, mobile-first, and privacy-conscious while giving users clear next-best actions month by month.',
  'FINANCE',
  'ALPHA',
  'Alpha',
  'Q3 2026',
  '["React Native","Decision Tree Engine","RevenueCat"]',
  '[{"text":"Dual onboarding for anonymous and personalized paths","completed":true},{"text":"Deterministic roadmap engine and step tracking","completed":true},{"text":"Multilingual UX across Spanish, English, and Italian","completed":true},{"text":"Letter generator and PDF export flow","completed":false},{"text":"Subscription rollout and customer restore flow","completed":false},{"text":"Compliance review and launch hardening","completed":false}]',
  '/brand/pasoscore-logo.png',
  '[]',
  '/contact',
  NULL,
  '["Deterministic Guidance Paths: Follow a clear month-by-month decision system instead of vague financial advice","Dual Onboarding: Start anonymously or use the more personalized path without exposing sensitive bureau data","Privacy-First Boundaries: No SSN collection, no credit report access, and mobile-local user data"]',
  'mobile',
  'published',
  58,
  'Free'
);

INSERT OR IGNORE INTO role_permissions (role, page, can_access) VALUES
  ('admin', 'updates', 1),
  ('admin', 'community', 1),
  ('moderator', 'updates', 1),
  ('moderator', 'community', 1);
