import { LevelConfig } from "./pointItOut.types";

export const LEVELS: LevelConfig[] = [
  {
    scene: "Living Room",
    sceneEmoji: "🛋️",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/living_room_full.png"),
    objects: [
      {
        id: "lr_car",
        name: "red car",
        emoji: "🚗",
        voiceFile: "find_red_car.mp3",
        x: 24,
        y: 85,
        width: 22,
        height: 14,
        found: false,
      },
      {
        id: "lr_teddy",
        name: "teddy bear",
        emoji: "🧸",
        voiceFile: "find_teddy_bear.mp3",
        x: 54,
        y: 51,
        width: 20,
        height: 30,
        found: false,
      },
      {
        id: "lr_apple",
        name: "green apple",
        emoji: "🍏",
        voiceFile: "find_green_apple.mp3",
        x: 28,
        y: 24,
        width: 8,
        height: 12,
        found: false,
      },
      {
        id: "lr_ball",
        name: "red ball",
        emoji: "⚽",
        voiceFile: "find_red_ball.mp3",
        x: 81,
        y: 84,
        width: 16,
        height: 16,
        found: false,
      },
      {
        id: "lr_book",
        name: "blue book",
        emoji: "📘",
        voiceFile: "find_blue_book.mp3",
        x: 81,
        y: 37,
        width: 6,
        height: 13,
        found: false,
      },
    ],
  },
  {
    scene: "Kitchen",
    sceneEmoji: "🍳",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/kitchen_full.png"),
    objects: [
      {
        id: "k_banana",
        name: "yellow banana",
        emoji: "🍌",
        voiceFile: "find_yellow_banana.mp3",
        x: 13,
        y: 57,
        width: 20,
        height: 15,
        found: false,
      },
      {
        id: "k_cup",
        name: "blue cup",
        emoji: "🥤",
        voiceFile: "find_blue_cup.mp3",
        x: 27,
        y: 42,
        width: 10,
        height: 12,
        found: false,
      },
      {
        id: "k_spoon",
        name: "white spoon",
        emoji: "🥄",
        voiceFile: "find_white_spoon.mp3",
        x: 68,
        y: 72,
        width: 18,
        height: 8,
        found: false,
      },
      {
        id: "k_jar",
        name: "cookie jar",
        emoji: "🍪",
        voiceFile: "find_cookie_jar.mp3",
        x: 64,
        y: 16,
        width: 15,
        height: 20,
        found: false,
      },
    ],
  },
  {
    scene: "Bedroom",
    sceneEmoji: "🛏️",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/bedroom_full.png"),
    objects: [
      {
        id: "b_robot",
        name: "toy robot",
        emoji: "🤖",
        voiceFile: "find_toy_robot.mp3",
        x: 25,
        y: 73,
        width: 22,
        height: 30,
        found: false,
      },
      {
        id: "b_flashlight",
        name: "flashlight",
        emoji: "🔦",
        voiceFile: "find_flashlight.mp3",
        x: 21,
        y: 47,
        width: 15,
        height: 10,
        found: false,
      },
      {
        id: "b_slippers",
        name: "slippers",
        emoji: "👟",
        voiceFile: "find_slippers.mp3",
        x: 58,
        y: 80,
        width: 25,
        height: 15,
        found: false,
      },
      {
        id: "b_pillow",
        name: "star pillow",
        emoji: "⭐",
        voiceFile: "find_star_pillow.mp3",
        x: 50,
        y: 39,
        width: 18,
        height: 18,
        found: false,
      },
    ],
  },
  {
    scene: "Playroom",
    sceneEmoji: "🎨",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/playroom_full.png"),
    objects: [
      {
        id: "p_block",
        name: "purple block",
        emoji: "🧱",
        voiceFile: "find_purple_block.mp3",
        x: 28,
        y: 75,
        width: 25,
        height: 22,
        found: false,
      },
      {
        id: "p_airplane",
        name: "toy airplane",
        emoji: "✈️",
        voiceFile: "find_toy_airplane.mp3",
        x: 71,
        y: 37,
        width: 20,
        height: 12,
        found: false,
      },
      {
        id: "p_top",
        name: "spinning top",
        emoji: "🌀",
        voiceFile: "find_spinning_top.mp3",
        x: 84,
        y: 62,
        width: 15,
        height: 15,
        found: false,
      },
      {
        id: "p_ball",
        name: "colorful ball",
        emoji: "🏐",
        voiceFile: "find_colorful_ball.mp3",
        x: 8,
        y: 57,
        width: 15,
        height: 15,
        found: false,
      },
    ],
  },
  {
    scene: "Garden",
    sceneEmoji: "🌻",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/garden_full.png"),
    objects: [
      {
        id: "g_watering_can",
        name: "watering can",
        emoji: "🚿",
        voiceFile: "find_watering_can.mp3",
        x: 15,
        y: 65,
        width: 25,
        height: 18,
        found: false,
      },
      {
        id: "g_trowel",
        name: "garden trowel",
        emoji: "⛏️",
        voiceFile: "find_garden_trowel.mp3",
        x: 78,
        y: 47,
        width: 18,
        height: 10,
        found: false,
      },
      {
        id: "g_ladybug",
        name: "ladybug",
        emoji: "🐞",
        voiceFile: "find_ladybug.mp3",
        x: 75,
        y: 60,
        width: 12,
        height: 12,
        found: false,
      },
      {
        id: "g_hat",
        name: "sun hat",
        emoji: "👒",
        voiceFile: "find_sun_hat.mp3",
        x: 64,
        y: 75,
        width: 20,
        height: 18,
        found: false,
      },
    ],
  },
  {
    scene: "Bathroom",
    sceneEmoji: "🛁",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/bathroom_full.png"),
    objects: [
      {
        id: "bath_duck",
        name: "yellow duck",
        emoji: "🦆",
        voiceFile: "find_yellow_duck.mp3",
        x: 13,
        y: 60,
        width: 15,
        height: 15,
        found: false,
      },
      {
        id: "bath_brush",
        name: "blue toothbrush",
        emoji: "🪥",
        voiceFile: "find_blue_toothbrush.mp3",
        x: 52,
        y: 39,
        width: 10,
        height: 15,
        found: false,
      },
      {
        id: "bath_shampoo",
        name: "green shampoo",
        emoji: "🧴",
        voiceFile: "find_green_shampoo.mp3",
        x: 41,
        y: 17,
        width: 10,
        height: 18,
        found: false,
      },
      {
        id: "bath_towel",
        name: "blue towel",
        emoji: "🧣",
        voiceFile: "find_blue_towel.mp3",
        x: 86,
        y: 62,
        width: 20,
        height: 25,
        found: false,
      },
    ],
  },
  {
    scene: "Garage",
    sceneEmoji: "🚗",
    backgroundImage: require("../../../assets/images/games/point_it_out/backgrounds/garage_full.png"),
    objects: [
      {
        id: "gar_bike",
        name: "red bicycle",
        emoji: "🚲",
        voiceFile: "find_red_bicycle.mp3",
        x: 16,
        y: 70,
        width: 30,
        height: 40,
        found: false,
      },
      {
        id: "gar_tools",
        name: "blue toolbox",
        emoji: "🧰",
        voiceFile: "find_blue_toolbox.mp3",
        x: 45,
        y: 42,
        width: 18,
        height: 20,
        found: false,
      },
      {
        id: "gar_ball",
        name: "soccer ball",
        emoji: "⚽",
        voiceFile: "find_soccer_ball.mp3",
        x: 58,
        y: 84,
        width: 15,
        height: 15,
        found: false,
      },
      {
        id: "gar_box",
        name: "cardboard box",
        emoji: "📦",
        voiceFile: "find_cardboard_box.mp3",
        x: 78,
        y: 79,
        width: 25,
        height: 28,
        found: false,
      },
    ],
  },
];
