Param(
    [string]$SourceProjectPath = "D:\dev\Northern Step Studio\apps\Northern Step Studio website",
    [string]$TargetFilePath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Resolve-TargetPath {
    Param([string]$ProvidedPath)

    if ($ProvidedPath -and $ProvidedPath.Trim().Length -gt 0) {
        return $ProvidedPath
    }

    $repoRoot = Split-Path -Path $PSScriptRoot -Parent
    return Join-Path $repoRoot "apps\backend-worker\.dev.vars"
}

function Parse-EnvFile {
    Param([string]$Path)

    $data = @{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $data
    }

    Get-Content -LiteralPath $Path | ForEach-Object {
        $line = $_.Trim()
        if ($line.Length -eq 0 -or $line.StartsWith("#")) {
            return
        }

        $idx = $line.IndexOf("=")
        if ($idx -lt 1) {
            return
        }

        $key = $line.Substring(0, $idx).Trim()
        $value = $line.Substring($idx + 1)
        if ($key.Length -gt 0) {
            $data[$key] = $value
        }
    }

    return $data
}

function Write-EnvFile {
    Param(
        [string]$Path,
        [hashtable]$Values
    )

    $directory = Split-Path -Path $Path -Parent
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory | Out-Null
    }

    $orderedKeys = @($Values.Keys | Sort-Object)
    $lines = @(
        "# Auto-generated by scripts/sync-worker-secrets-from-website.ps1",
        "# Local-only file. Do not commit."
    )

    foreach ($key in $orderedKeys) {
        $lines += "$key=$($Values[$key])"
    }

    Set-Content -LiteralPath $Path -Value $lines -Encoding UTF8
}

$targetPath = Resolve-TargetPath -ProvidedPath $TargetFilePath

if (-not (Test-Path -LiteralPath $SourceProjectPath)) {
    throw "Source project path not found: $SourceProjectPath"
}

$sourceFiles = @(
    ".dev.vars",
    ".env.local",
    ".env",
    ".env.production",
    ".env.development"
) | ForEach-Object { Join-Path $SourceProjectPath $_ }

$sourceData = @{}
foreach ($file in $sourceFiles) {
    $parsed = Parse-EnvFile -Path $file
    foreach ($key in $parsed.Keys) {
        if (-not $sourceData.ContainsKey($key)) {
            $sourceData[$key] = $parsed[$key]
        }
    }
}

$targetData = @{}
if (Test-Path -LiteralPath $targetPath) {
    $targetData = Parse-EnvFile -Path $targetPath
} else {
    $repoRoot = Split-Path -Path $PSScriptRoot -Parent
    $examplePath = Join-Path $repoRoot "apps\backend-worker\.dev.vars.example"
    if (Test-Path -LiteralPath $examplePath) {
        $targetData = Parse-EnvFile -Path $examplePath
    }
}

$syncMap = @{
    "RESEND_API_KEY"      = @("RESEND_API_KEY")
    "EMAIL_FROM"          = @("EMAIL_FROM", "RESEND_FROM_EMAIL")
    "GOOGLE_CLIENT_ID"    = @("GOOGLE_CLIENT_ID", "VITE_GOOGLE_CLIENT_ID")
    "GOOGLE_CLIENT_SECRET" = @("GOOGLE_CLIENT_SECRET")
    "SUPABASE_SERVICE_ROLE_KEY" = @("SUPABASE_SERVICE_ROLE_KEY")
    "REVENUECAT_WEBHOOK_SECRET" = @("REVENUECAT_WEBHOOK_SECRET")
    "REVENUECAT_API_KEY" = @("REVENUECAT_API_KEY")
}

$updatedKeys = @()
$missingKeys = @()

foreach ($targetKey in $syncMap.Keys) {
    $candidates = $syncMap[$targetKey]
    $resolved = $null

    foreach ($candidate in $candidates) {
        if ($sourceData.ContainsKey($candidate) -and $sourceData[$candidate].ToString().Trim().Length -gt 0) {
            $resolved = $sourceData[$candidate]
            break
        }
    }

    if ($null -ne $resolved) {
        $targetData[$targetKey] = $resolved
        $updatedKeys += $targetKey
    } else {
        $missingKeys += $targetKey
    }
}

Write-EnvFile -Path $targetPath -Values $targetData

Write-Host "Synced worker secrets file:" $targetPath
if ($updatedKeys.Count -gt 0) {
    Write-Host "Updated keys:" ($updatedKeys -join ", ")
}
if ($missingKeys.Count -gt 0) {
    Write-Warning ("Missing in source project: " + ($missingKeys -join ", "))
}
