import { Animal } from "./animalSounds.types";

export const ANIMALS: Animal[] = [
  // Farm Animals
  {
    name: "dog",
    emoji: "🐶",
    sound: "Woof woof!",
    voiceKey: "who says woof woof",
    soundKey: "woof woof",
    category: "farm",
  },
  {
    name: "cat",
    emoji: "🐱",
    sound: "Meow!",
    voiceKey: "who says meow",
    soundKey: "meow",
    category: "pet",
  },
  {
    name: "cow",
    emoji: "🐮",
    sound: "Moo!",
    voiceKey: "who says moo",
    soundKey: "moo",
    category: "farm",
  },
  {
    name: "pig",
    emoji: "🐷",
    sound: "Oink oink!",
    voiceKey: "who says oink oink",
    soundKey: "oink oink",
    category: "farm",
  },
  {
    name: "horse",
    emoji: "🐴",
    sound: "Neigh!",
    voiceKey: "who says neigh",
    soundKey: "neigh",
    category: "farm",
  },
  {
    name: "sheep",
    emoji: "🐑",
    sound: "Baa!",
    voiceKey: "who says baa",
    soundKey: "baa",
    category: "farm",
  },
  {
    name: "goat",
    emoji: "🐐",
    sound: "Meh!",
    voiceKey: "who says meh",
    soundKey: "meh",
    category: "farm",
  },
  {
    name: "rooster",
    emoji: "🐓",
    sound: "Cock-a-doodle-doo!",
    voiceKey: "who says cock a doodle doo",
    soundKey: "cock a doodle doo",
    category: "farm",
  },
  {
    name: "chicken",
    emoji: "🐔",
    sound: "Cluck cluck!",
    voiceKey: "who says cluck cluck",
    soundKey: "cluck cluck",
    category: "farm",
  },
  {
    name: "duck",
    emoji: "🦆",
    sound: "Quack!",
    voiceKey: "who says quack",
    soundKey: "quack",
    category: "bird",
  },
  {
    name: "turkey",
    emoji: "🦃",
    sound: "Gobble gobble!",
    voiceKey: "who says gobble gobble",
    soundKey: "gobble gobble",
    category: "bird",
  },
  // Wild Animals
  {
    name: "lion",
    emoji: "🦁",
    sound: "Roar!",
    voiceKey: "who says roar",
    soundKey: "roar",
    category: "wild",
  },
  {
    name: "elephant",
    emoji: "🐘",
    sound: "Trumpet!",
    voiceKey: "who says trumpet",
    soundKey: "trumpet",
    category: "wild",
  },
  {
    name: "monkey",
    emoji: "🐵",
    sound: "Ooh ooh ah ah!",
    voiceKey: "who says ooh ooh ah ah",
    soundKey: "ooh ooh ah ah",
    category: "wild",
  },
  {
    name: "bear",
    emoji: "🐻",
    sound: "Growl!",
    voiceKey: "who says growl",
    soundKey: "growl",
    category: "wild",
  },
  {
    name: "wolf",
    emoji: "🐺",
    sound: "Howl!",
    voiceKey: "who says howl",
    soundKey: "howl",
    category: "wild",
  },
  {
    name: "frog",
    emoji: "🐸",
    sound: "Ribbit!",
    voiceKey: "who says ribbit",
    soundKey: "ribbit",
    category: "wild",
  },
  {
    name: "snake",
    emoji: "🐍",
    sound: "Hiss!",
    voiceKey: "who says hiss",
    soundKey: "hiss",
    category: "wild",
  },
  {
    name: "gorilla",
    emoji: "🦍",
    sound: "Ugh ugh!",
    voiceKey: "who says ugh ugh",
    soundKey: "ugh ugh",
    category: "wild",
  },
  {
    name: "zebra",
    emoji: "🦓",
    sound: "Bark!",
    voiceKey: "who says bark",
    soundKey: "bark",
    category: "wild",
  },
  // Birds
  {
    name: "bird",
    emoji: "🐦",
    sound: "Tweet tweet!",
    voiceKey: "who says tweet tweet",
    soundKey: "tweet tweet",
    category: "bird",
  },
  {
    name: "owl",
    emoji: "🦉",
    sound: "Hoot hoot!",
    voiceKey: "who says hoot hoot",
    soundKey: "hoot hoot",
    category: "bird",
  },
  {
    name: "parrot",
    emoji: "🦜",
    sound: "Squawk!",
    voiceKey: "who says squawk",
    soundKey: "squawk",
    category: "bird",
  },
  {
    name: "crow",
    emoji: "🐦‍⬛",
    sound: "Caw caw!",
    voiceKey: "who says caw caw",
    soundKey: "caw caw",
    category: "bird",
  },
  {
    name: "eagle",
    emoji: "🦅",
    sound: "Screech!",
    voiceKey: "who says screech",
    soundKey: "screech",
    category: "bird",
  },
  {
    name: "penguin",
    emoji: "🐧",
    sound: "Honk!",
    voiceKey: "who says honk",
    soundKey: "honk",
    category: "bird",
  },
  // Sea Creatures
  {
    name: "dolphin",
    emoji: "🐬",
    sound: "Click click!",
    voiceKey: "who says click click",
    soundKey: "click click",
    category: "sea",
  },
  {
    name: "whale",
    emoji: "🐋",
    sound: "Whooo!",
    voiceKey: "who says whooo",
    soundKey: "whooo",
    category: "sea",
  },
  {
    name: "seal",
    emoji: "🦭",
    sound: "Arp arp!",
    voiceKey: "who says arp arp",
    soundKey: "arp arp",
    category: "sea",
  },
  {
    name: "fish",
    emoji: "🐟",
    sound: "Blub blub!",
    voiceKey: "who says blub blub",
    soundKey: "blub blub",
    category: "sea",
  },
  {
    name: "crab",
    emoji: "🦀",
    sound: "Click clack!",
    voiceKey: "who says click clack",
    soundKey: "click clack",
    category: "sea",
  },
  // More Pets & Others
  {
    name: "mouse",
    emoji: "🐭",
    sound: "Squeak!",
    voiceKey: "who says squeak",
    soundKey: "squeak",
    category: "pet",
  },
  {
    name: "chick",
    emoji: "🐥",
    sound: "Cheep cheep!",
    voiceKey: "who says cheep cheep",
    soundKey: "cheep cheep",
    category: "farm",
  },
  {
    name: "tiger",
    emoji: "🐯",
    sound: "Grrr Roar!",
    voiceKey: "who says roar",
    soundKey: "roar",
    category: "wild",
  },
  {
    name: "bee",
    emoji: "🐝",
    sound: "Buzz!",
    voiceKey: "who says buzz",
    soundKey: "buzz",
    category: "wild",
  },
  {
    name: "dinosaur",
    emoji: "🦖",
    sound: "RAWR!",
    voiceKey: "who says rawr",
    soundKey: "rawr",
    category: "wild",
  },
];
