import { Audio } from 'expo-av';

// Voice Assets Registry
// Map of predictable phrases to their asset files
export const VOICE_ASSETS: Record<string, any> = {
    // Color Match Instructions
    'find the red color': require('../../assets/sounds/voice/find_red.mp3'),
    'find the blue color': require('../../assets/sounds/voice/find_blue.mp3'),
    'find the green color': require('../../assets/sounds/voice/find_green.mp3'),
    'find the yellow color': require('../../assets/sounds/voice/find_yellow.mp3'),
    'find the purple color': require('../../assets/sounds/voice/find_purple.mp3'),
    'find the orange color': require('../../assets/sounds/voice/find_orange.mp3'),
    'find the pink color': require('../../assets/sounds/voice/find_pink.mp3'),
    'find the cyan color': require('../../assets/sounds/voice/find_cyan.mp3'),
    'find the lime color': require('../../assets/sounds/voice/find_lime.mp3'),
    'find the teal color': require('../../assets/sounds/voice/find_teal.mp3'),
    'find the brown color': require('../../assets/sounds/voice/find_brown.mp3'),

    // Yes/No Game Instructions
    'is this an apple': require('../../assets/sounds/voice/yesno_apple.mp3'),
    'is this a dog': require('../../assets/sounds/voice/yesno_dog.mp3'),
    'is this a car': require('../../assets/sounds/voice/yesno_car.mp3'),
    'is this a fish': require('../../assets/sounds/voice/yesno_fish.mp3'),
    'is this a bird': require('../../assets/sounds/voice/yesno_bird.mp3'),
    'is this a cat': require('../../assets/sounds/voice/yesno_cat.mp3'),

    'is the sun yellow': require('../../assets/sounds/voice/yesno_sun_yellow.mp3'),
    'is the grass green': require('../../assets/sounds/voice/yesno_grass_green.mp3'),
    'is the sky blue': require('../../assets/sounds/voice/yesno_sky_blue.mp3'),
    'is a strawberry red': require('../../assets/sounds/voice/yesno_strawberry_red.mp3'),
    'is a lemon purple': require('../../assets/sounds/voice/yesno_lemon_purple.mp3'),
    'is snow black': require('../../assets/sounds/voice/yesno_snow_black.mp3'),

    'do cats meow': require('../../assets/sounds/voice/yesno_cats_meow.mp3'),
    'do birds fly': require('../../assets/sounds/voice/yesno_birds_fly.mp3'),
    'do fish walk': require('../../assets/sounds/voice/yesno_fish_walk.mp3'),
    'do dogs quack': require('../../assets/sounds/voice/yesno_dogs_quack.mp3'),
    'do cows moo': require('../../assets/sounds/voice/yesno_cows_moo.mp3'),
    'do snakes run': require('../../assets/sounds/voice/yesno_snakes_run.mp3'),

    'is ice cold': require('../../assets/sounds/voice/yesno_ice_cold.mp3'),
    'is fire hot': require('../../assets/sounds/voice/yesno_fire_hot.mp3'),
    'is a rock soft': require('../../assets/sounds/voice/yesno_rock_soft.mp3'),
    'is candy sweet': require('../../assets/sounds/voice/yesno_candy_sweet.mp3'),
    'do clean cars fly': require('../../assets/sounds/voice/yesno_cars_fly.mp3'),
    'is rain dry': require('../../assets/sounds/voice/yesno_rain_dry.mp3'),

    // Pop Bubbles
    'pop the bubbles': require('../../assets/sounds/voice/pop_bubbles.mp3'),
    'all popped hurray': require('../../assets/sounds/voice/pop_all_hurray.mp3'),

    // Tracing Feedback
    'perfect tracing': require('../../assets/sounds/voice/trace_perfect.mp3'),
    'perfect letter': require('../../assets/sounds/voice/trace_letter_perfect.mp3'),
    'stay on the line': require('../../assets/sounds/voice/trace_error.mp3'),
    'try to stay inside': require('../../assets/sounds/voice/trace_error.mp3'),
    'trace more': require('../../assets/sounds/voice/trace_error.mp3'),

    // Stacking
    'stack the blocks': require('../../assets/sounds/voice/stack_intro.mp3'),
    'build it high': require('../../assets/sounds/voice/stack_intro.mp3'),
    'start here': require('../../assets/sounds/voice/stack_start_here.mp3'),
    'tower built': require('../../assets/sounds/voice/stack_tower_built.mp3'),
    'oh no it fell': require('../../assets/sounds/voice/stack_fall.mp3'),

    // Tower Counting

    '0': require('../../assets/sounds/voice/say_0.mp3'),
    '1': require('../../assets/sounds/voice/say_1.mp3'),
    '2': require('../../assets/sounds/voice/say_2.mp3'),
    '3': require('../../assets/sounds/voice/say_3.mp3'),
    '4': require('../../assets/sounds/voice/say_4.mp3'),
    '5': require('../../assets/sounds/voice/say_5.mp3'),
    '6': require('../../assets/sounds/voice/say_6.mp3'),
    '7': require('../../assets/sounds/voice/say_7.mp3'),
    '8': require('../../assets/sounds/voice/say_8.mp3'),
    '9': require('../../assets/sounds/voice/say_9.mp3'),

    // Number Tracing Instructions
    'trace the number 0': require('../../assets/sounds/voice/trace_number_0.mp3'),
    'trace the number 1': require('../../assets/sounds/voice/trace_number_1.mp3'),
    'trace the number 2': require('../../assets/sounds/voice/trace_number_2.mp3'),
    'trace the number 3': require('../../assets/sounds/voice/trace_number_3.mp3'),
    'trace the number 4': require('../../assets/sounds/voice/trace_number_4.mp3'),
    'trace the number 5': require('../../assets/sounds/voice/trace_number_5.mp3'),
    'trace the number 6': require('../../assets/sounds/voice/trace_number_6.mp3'),
    'trace the number 7': require('../../assets/sounds/voice/trace_number_7.mp3'),
    'trace the number 8': require('../../assets/sounds/voice/trace_number_8.mp3'),
    'trace the number 9': require('../../assets/sounds/voice/trace_number_9.mp3'),

    // Letters A-Z (for letter tracing)
    'a': require('../../assets/sounds/voice/say_A.mp3'),
    'b': require('../../assets/sounds/voice/say_B.mp3'),
    'c': require('../../assets/sounds/voice/say_C.mp3'),
    'd': require('../../assets/sounds/voice/say_D.mp3'),
    'e': require('../../assets/sounds/voice/say_E.mp3'),
    'f': require('../../assets/sounds/voice/say_F.mp3'),
    'g': require('../../assets/sounds/voice/say_G.mp3'),
    'h': require('../../assets/sounds/voice/say_H.mp3'),
    'i': require('../../assets/sounds/voice/say_I.mp3'),
    'j': require('../../assets/sounds/voice/say_J.mp3'),
    'k': require('../../assets/sounds/voice/say_K.mp3'),
    'l': require('../../assets/sounds/voice/say_L.mp3'),
    'm': require('../../assets/sounds/voice/say_M.mp3'),
    'n': require('../../assets/sounds/voice/say_N.mp3'),
    'o': require('../../assets/sounds/voice/say_O.mp3'),
    'p': require('../../assets/sounds/voice/say_P.mp3'),
    'q': require('../../assets/sounds/voice/say_Q.mp3'),
    'r': require('../../assets/sounds/voice/say_R.mp3'),
    's': require('../../assets/sounds/voice/say_S.mp3'),
    't': require('../../assets/sounds/voice/say_T.mp3'),
    'u': require('../../assets/sounds/voice/say_U.mp3'),
    'v': require('../../assets/sounds/voice/say_V.mp3'),
    'w': require('../../assets/sounds/voice/say_W.mp3'),
    'x': require('../../assets/sounds/voice/say_X.mp3'),
    'y': require('../../assets/sounds/voice/say_Y.mp3'),
    'z': require('../../assets/sounds/voice/say_Z.mp3'),

    // Shape Sorting
    'drag the circle': require('../../assets/sounds/voice/drag_circle.mp3'),
    'drag the square': require('../../assets/sounds/voice/drag_square.mp3'),
    'drag the triangle': require('../../assets/sounds/voice/drag_triangle.mp3'),
    'drag the star': require('../../assets/sounds/voice/drag_star.mp3'),
    'drag the heart': require('../../assets/sounds/voice/drag_heart.mp3'),
    'drag the pentagon': require('../../assets/sounds/voice/drag_pentagon.mp3'),
    'drag the hexagon': require('../../assets/sounds/voice/drag_hexagon.mp3'),
    'drag the diamond': require('../../assets/sounds/voice/drag_diamond.mp3'),
    'perfect fit': require('../../assets/sounds/voice/shape_success.mp3'),
    'not that one': require('../../assets/sounds/voice/shape_error.mp3'),

    // Magic Fingers
    'tap the thumb': require('../../assets/sounds/voice/magic_intro.mp3'),
    'follow the pattern': require('../../assets/sounds/voice/magic_pattern.mp3'),
    'tap finger one': require('../../assets/sounds/voice/tap_finger_1.mp3'),
    'tap finger two': require('../../assets/sounds/voice/tap_finger_2.mp3'),
    'tap finger three': require('../../assets/sounds/voice/tap_finger_3.mp3'),
    'tap finger four': require('../../assets/sounds/voice/tap_finger_4.mp3'),
    'tap finger five': require('../../assets/sounds/voice/tap_finger_5.mp3'),

    // Feedback
    'great job': require('../../assets/sounds/voice/feedback_success.mp3'),
    'try again': require('../../assets/sounds/voice/feedback_retry.mp3'),
    'yes correct': require('../../assets/sounds/voice/feedback_yes_correct.mp3'),
    'no correct': require('../../assets/sounds/voice/feedback_no_correct.mp3'),
    'oops try again': require('../../assets/sounds/voice/feedback_oops.mp3'),

    // Point It Out Game
    'find the red car': require('../../assets/sounds/voice/find_red_car.mp3'),
    'find the teddy bear': require('../../assets/sounds/voice/find_teddy_bear.mp3'),
    'find the green apple': require('../../assets/sounds/voice/find_green_apple.mp3'),
    'find the red ball': require('../../assets/sounds/voice/find_red_ball.mp3'),
    'find the blue book': require('../../assets/sounds/voice/find_blue_book.mp3'),
    'find the yellow banana': require('../../assets/sounds/voice/find_yellow_banana.mp3'),
    'find the blue cup': require('../../assets/sounds/voice/find_blue_cup.mp3'),
    'find the white spoon': require('../../assets/sounds/voice/find_white_spoon.mp3'),
    'find the cookie jar': require('../../assets/sounds/voice/find_cookie_jar.mp3'),
    'find the toy robot': require('../../assets/sounds/voice/find_toy_robot.mp3'),
    'find the flashlight': require('../../assets/sounds/voice/find_flashlight.mp3'),
    'find the slippers': require('../../assets/sounds/voice/find_slippers.mp3'),
    'find the star pillow': require('../../assets/sounds/voice/find_star_pillow.mp3'),
    'find the purple block': require('../../assets/sounds/voice/find_purple_block.mp3'),
    'find the toy airplane': require('../../assets/sounds/voice/find_toy_airplane.mp3'),
    'find the spinning top': require('../../assets/sounds/voice/find_spinning_top.mp3'),
    'find the colorful ball': require('../../assets/sounds/voice/find_colorful_ball.mp3'),
    'find the watering can': require('../../assets/sounds/voice/find_watering_can.mp3'),
    'find the garden trowel': require('../../assets/sounds/voice/find_garden_trowel.mp3'),
    'find the ladybug': require('../../assets/sounds/voice/find_ladybug.mp3'),
    'find the sun hat': require('../../assets/sounds/voice/find_sun_hat.mp3'),

    // Bathroom (Expansion)
    'find the yellow duck': require('../../assets/sounds/voice/find_yellow_duck.mp3'),
    'find the green shampoo': require('../../assets/sounds/voice/find_green_shampoo.mp3'),
    'find the blue toothbrush': require('../../assets/sounds/voice/find_blue_toothbrush.mp3'),
    'find the blue towel': require('../../assets/sounds/voice/find_blue_towel.mp3'),

    // Garage (Expansion)
    'find the red bicycle': require('../../assets/sounds/voice/find_red_bicycle.mp3'),
    'find the blue toolbox': require('../../assets/sounds/voice/find_blue_toolbox.mp3'),
    'find the soccer ball': require('../../assets/sounds/voice/find_soccer_ball.mp3'),
    'find the cardboard box': require('../../assets/sounds/voice/find_cardboard_box.mp3'),

    // Emotions Game
    'find the happy face': require('../../assets/sounds/voice/find_happy.mp3'),
    'find the sad face': require('../../assets/sounds/voice/find_sad.mp3'),
    'find the angry face': require('../../assets/sounds/voice/find_angry.mp3'),
    'find the surprised face': require('../../assets/sounds/voice/find_surprised.mp3'),
    'find the scared face': require('../../assets/sounds/voice/find_scared.mp3'),
    'find the sleepy face': require('../../assets/sounds/voice/find_sleepy.mp3'),
    'find the silly face': require('../../assets/sounds/voice/find_silly.mp3'),
    'find the loving face': require('../../assets/sounds/voice/find_loving.mp3'),

    'yes that is happy': require('../../assets/sounds/voice/that_is_happy.mp3'),
    'yes that is sad': require('../../assets/sounds/voice/that_is_sad.mp3'),
    'yes that is angry': require('../../assets/sounds/voice/that_is_angry.mp3'),
    'yes that is surprised': require('../../assets/sounds/voice/that_is_surprised.mp3'),
    'yes that is scared': require('../../assets/sounds/voice/that_is_scared.mp3'),
    'yes that is sleepy': require('../../assets/sounds/voice/that_is_sleepy.mp3'),
    'yes that is silly': require('../../assets/sounds/voice/that_is_silly.mp3'),
    'yes that is loving': require('../../assets/sounds/voice/that_is_loving.mp3'),

    // Size Ordering
    'put them in order from smallest to largest': require('../../assets/sounds/voice/order_smallest_largest.mp3'),
    'perfect order': require('../../assets/sounds/voice/order_perfect.mp3'),
    'try smallest to largest': require('../../assets/sounds/voice/order_error.mp3'),

    // Animal Sounds - Question Prompts
    'who says woof woof': require('../../assets/sounds/voice/who_says_woof.mp3'),
    'who says meow': require('../../assets/sounds/voice/who_says_meow.mp3'),
    'who says moo': require('../../assets/sounds/voice/who_says_moo.mp3'),
    'who says oink oink': require('../../assets/sounds/voice/who_says_oink.mp3'),
    'who says neigh': require('../../assets/sounds/voice/who_says_neigh.mp3'),
    'who says baa': require('../../assets/sounds/voice/who_says_baa.mp3'),
    'who says meh': require('../../assets/sounds/voice/who_says_meh.mp3'),
    'who says cock a doodle doo': require('../../assets/sounds/voice/who_says_cockadoodledoo.mp3'),
    'who says cluck cluck': require('../../assets/sounds/voice/who_says_cluck.mp3'),
    'who says quack': require('../../assets/sounds/voice/who_says_quack.mp3'),
    'who says gobble gobble': require('../../assets/sounds/voice/who_says_gobble.mp3'),
    'who says roar': require('../../assets/sounds/voice/who_says_roar.mp3'),
    'who says trumpet': require('../../assets/sounds/voice/who_says_trumpet.mp3'),
    'who says ooh ooh ah ah': require('../../assets/sounds/voice/who_says_oohaah.mp3'),
    'who says growl': require('../../assets/sounds/voice/who_says_growl.mp3'),
    'who says howl': require('../../assets/sounds/voice/who_says_howl.mp3'),
    'who says ribbit': require('../../assets/sounds/voice/who_says_ribbit.mp3'),
    'who says hiss': require('../../assets/sounds/voice/who_says_hiss.mp3'),
    'who says hoot hoot': require('../../assets/sounds/voice/who_says_hoot.mp3'),
    'who says buzz': require('../../assets/sounds/voice/who_says_buzz.mp3'),
    'who says tweet tweet': require('../../assets/sounds/voice/who_says_tweet.mp3'),
    'who says squawk': require('../../assets/sounds/voice/who_says_squawk.mp3'),
    'who says caw caw': require('../../assets/sounds/voice/who_says_caw.mp3'),
    'who says screech': require('../../assets/sounds/voice/who_says_screech.mp3'),
    'who says honk': require('../../assets/sounds/voice/who_says_honk.mp3'),
    'who says click click': require('../../assets/sounds/voice/who_says_click.mp3'),
    'who says whooo': require('../../assets/sounds/voice/who_says_whoo.mp3'),
    'who says arp arp': require('../../assets/sounds/voice/who_says_arp.mp3'),
    'who says blub blub': require('../../assets/sounds/voice/who_says_blub.mp3'),
    'who says click clack': require('../../assets/sounds/voice/who_says_clickclack.mp3'),
    'who says squeak': require('../../assets/sounds/voice/who_says_squeak.mp3'),
    'who says thump thump': require('../../assets/sounds/voice/who_says_thump.mp3'),
    'who says rawr': require('../../assets/sounds/voice/who_says_rawr.mp3'),
    'who says ugh ugh': require('../../assets/sounds/voice/who_says_ugh.mp3'),
    'who says bark': require('../../assets/sounds/voice/who_says_bark.mp3'),

    // Animal Sounds - Confirmations
    'yes thats a dog': require('../../assets/sounds/voice/yes_dog.mp3'),
    'yes thats a cat': require('../../assets/sounds/voice/yes_cat.mp3'),
    'yes thats a cow': require('../../assets/sounds/voice/yes_cow.mp3'),
    'yes thats a pig': require('../../assets/sounds/voice/yes_pig.mp3'),
    'yes thats a horse': require('../../assets/sounds/voice/yes_horse.mp3'),
    'yes thats a sheep': require('../../assets/sounds/voice/yes_sheep.mp3'),
    'yes thats a goat': require('../../assets/sounds/voice/yes_goat.mp3'),
    'yes thats a rooster': require('../../assets/sounds/voice/yes_rooster.mp3'),
    'yes thats a chicken': require('../../assets/sounds/voice/yes_chicken.mp3'),
    'yes thats a duck': require('../../assets/sounds/voice/yes_duck.mp3'),
    'yes thats a turkey': require('../../assets/sounds/voice/yes_turkey.mp3'),
    'yes thats a lion': require('../../assets/sounds/voice/yes_lion.mp3'),
    'yes thats an elephant': require('../../assets/sounds/voice/yes_elephant.mp3'),
    'yes thats a monkey': require('../../assets/sounds/voice/yes_monkey.mp3'),
    'yes thats a bear': require('../../assets/sounds/voice/yes_bear.mp3'),
    'yes thats a wolf': require('../../assets/sounds/voice/yes_wolf.mp3'),
    'yes thats a frog': require('../../assets/sounds/voice/yes_frog.mp3'),
    'yes thats a snake': require('../../assets/sounds/voice/yes_snake.mp3'),
    'yes thats an owl': require('../../assets/sounds/voice/yes_owl.mp3'),
    'yes thats a bee': require('../../assets/sounds/voice/yes_bee.mp3'),
    'yes thats a bird': require('../../assets/sounds/voice/yes_bird.mp3'),
    'yes thats a parrot': require('../../assets/sounds/voice/yes_parrot.mp3'),
    'yes thats a crow': require('../../assets/sounds/voice/yes_crow.mp3'),
    'yes thats an eagle': require('../../assets/sounds/voice/yes_eagle.mp3'),
    'yes thats a penguin': require('../../assets/sounds/voice/yes_penguin.mp3'),
    'yes thats a dolphin': require('../../assets/sounds/voice/yes_dolphin.mp3'),
    'yes thats a whale': require('../../assets/sounds/voice/yes_whale.mp3'),
    'yes thats a seal': require('../../assets/sounds/voice/yes_seal.mp3'),
    'yes thats a fish': require('../../assets/sounds/voice/yes_fish.mp3'),
    'yes thats a crab': require('../../assets/sounds/voice/yes_crab.mp3'),
    'yes thats a mouse': require('../../assets/sounds/voice/yes_mouse.mp3'),
    'yes thats a hamster': require('../../assets/sounds/voice/yes_hamster.mp3'),
    'yes thats a tiger': require('../../assets/sounds/voice/yes_tiger.mp3'),
    'yes thats a gorilla': require('../../assets/sounds/voice/yes_gorilla.mp3'),
    'yes thats a zebra': require('../../assets/sounds/voice/yes_zebra.mp3'),
    'yes thats a dinosaur': require('../../assets/sounds/voice/yes_dinosaur.mp3'),

    // Animal sounds ONLY (for tap feedback)
    'woof woof': require('../../assets/sounds/voice/sound_woof.mp3'),
    'meow': require('../../assets/sounds/voice/sound_meow.mp3'),
    'moo': require('../../assets/sounds/voice/sound_moo.mp3'),
    'oink oink': require('../../assets/sounds/voice/sound_oink.mp3'),
    'neigh': require('../../assets/sounds/voice/sound_neigh.mp3'),
    'baa': require('../../assets/sounds/voice/sound_baa.mp3'),
    'meh': require('../../assets/sounds/voice/sound_meh.mp3'),
    'cock a doodle doo': require('../../assets/sounds/voice/sound_cockadoodledoo.mp3'),
    'cluck cluck': require('../../assets/sounds/voice/sound_cluck.mp3'),
    'quack': require('../../assets/sounds/voice/sound_quack.mp3'),
    'gobble gobble': require('../../assets/sounds/voice/sound_gobble.mp3'),
    'roar': require('../../assets/sounds/voice/sound_roar.mp3'),
    'trumpet': require('../../assets/sounds/voice/sound_trumpet.mp3'),
    'ooh ooh ah ah': require('../../assets/sounds/voice/sound_oohaah.mp3'),
    'growl': require('../../assets/sounds/voice/sound_growl.mp3'),
    'howl': require('../../assets/sounds/voice/sound_howl.mp3'),
    'ribbit': require('../../assets/sounds/voice/sound_ribbit.mp3'),
    'hiss': require('../../assets/sounds/voice/sound_hiss.mp3'),
    'hoot hoot': require('../../assets/sounds/voice/sound_hoot.mp3'),
    'buzz': require('../../assets/sounds/voice/sound_buzz.mp3'),
    'tweet tweet': require('../../assets/sounds/voice/sound_tweet.mp3'),
    'squawk': require('../../assets/sounds/voice/sound_squawk.mp3'),
    'caw caw': require('../../assets/sounds/voice/sound_caw.mp3'),
    'screech': require('../../assets/sounds/voice/sound_screech.mp3'),
    'honk': require('../../assets/sounds/voice/sound_honk.mp3'),
    'click click': require('../../assets/sounds/voice/sound_click.mp3'),
    'whooo': require('../../assets/sounds/voice/sound_whoo.mp3'),
    'arp arp': require('../../assets/sounds/voice/sound_arp.mp3'),
    'blub blub': require('../../assets/sounds/voice/sound_blub.mp3'),
    'click clack': require('../../assets/sounds/voice/sound_clickclack.mp3'),
    'squeak': require('../../assets/sounds/voice/sound_squeak.mp3'),
    'rawr': require('../../assets/sounds/voice/sound_rawr.mp3'),
    'ugh ugh': require('../../assets/sounds/voice/sound_ugh.mp3'),
    'bark': require('../../assets/sounds/voice/sound_bark.mp3'),
};

/**
 * Normalizes text to a key (lowercase, trimmed) to find matching asset
 */
export function getVoiceAsset(text: string): any | null {
    const key = text.toLowerCase().trim();

    // 1. Exact or punct-removed match (Full Phrases or existing assets)
    if (VOICE_ASSETS[key]) return VOICE_ASSETS[key];
    const cleanKey = key.replace(/[!.,?]/g, '');
    if (VOICE_ASSETS[cleanKey]) return VOICE_ASSETS[cleanKey];

    return null;
}
