/**
 * 🖥️ PC PARTS KNOWLEDGE DATABASE
 * 
 * Comprehensive database of PC components with specifications.
 * Used by Nexus AI to answer questions about specific parts.
 */

// --- NVIDIA CONSUMER GPUs ---
export const NVIDIA_CONSUMER_GPUS = {
    // RTX 40 Series
    'rtx 4090': {
        name: 'NVIDIA GeForce RTX 4090',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '24GB GDDR6X',
        memoryBus: '384-bit',
        cudaCores: 16384,
        baseClock: '2.23 GHz',
        boostClock: '2.52 GHz',
        tdp: 450,
        msrp: 1599,
        releaseYear: 2022,
        performance: 'Best consumer GPU. Handles 4K 120+ FPS in most games. Overkill for 1080p.',
        goodFor: ['4K gaming', 'VR', 'AI/ML workloads', 'Content creation', '3D rendering'],
        psuRecommendation: '850W minimum',
        competitors: ['RTX 4080 Super', 'RX 7900 XTX'],
    },
    'rtx 4080 super': {
        name: 'NVIDIA GeForce RTX 4080 Super',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '16GB GDDR6X',
        memoryBus: '256-bit',
        cudaCores: 10240,
        baseClock: '2.29 GHz',
        boostClock: '2.55 GHz',
        tdp: 320,
        msrp: 999,
        releaseYear: 2024,
        performance: 'Excellent 4K GPU. 60-100+ FPS at 4K with ray tracing.',
        goodFor: ['4K gaming', 'High refresh 1440p', 'Streaming', 'Content creation'],
        psuRecommendation: '750W minimum',
        competitors: ['RTX 4090', 'RX 7900 XTX'],
    },
    'rtx 4080': {
        name: 'NVIDIA GeForce RTX 4080',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '16GB GDDR6X',
        memoryBus: '256-bit',
        cudaCores: 9728,
        baseClock: '2.21 GHz',
        boostClock: '2.51 GHz',
        tdp: 320,
        msrp: 1199,
        releaseYear: 2022,
        performance: 'Excellent 4K gaming. Replaced by RTX 4080 Super.',
        goodFor: ['4K gaming', '1440p high refresh', 'Streaming'],
        psuRecommendation: '750W minimum',
        competitors: ['RTX 4080 Super', 'RX 7900 XT'],
    },
    'rtx 4070 ti super': {
        name: 'NVIDIA GeForce RTX 4070 Ti Super',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '16GB GDDR6X',
        memoryBus: '256-bit',
        cudaCores: 8448,
        baseClock: '2.34 GHz',
        boostClock: '2.61 GHz',
        tdp: 285,
        msrp: 799,
        releaseYear: 2024,
        performance: 'Great 1440p and good 4K performance.',
        goodFor: ['1440p 144Hz', '4K 60Hz', 'Content creation'],
        psuRecommendation: '700W minimum',
        competitors: ['RTX 4070 Super', 'RX 7800 XT'],
    },
    'rtx 4070 super': {
        name: 'NVIDIA GeForce RTX 4070 Super',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '12GB GDDR6X',
        memoryBus: '192-bit',
        cudaCores: 7168,
        baseClock: '1.98 GHz',
        boostClock: '2.48 GHz',
        tdp: 220,
        msrp: 599,
        releaseYear: 2024,
        performance: 'Best value for 1440p gaming. Sweet spot GPU.',
        goodFor: ['1440p gaming', '1080p 240Hz', 'Streaming'],
        psuRecommendation: '650W minimum',
        competitors: ['RX 7800 XT', 'RTX 4070'],
    },
    'rtx 4070': {
        name: 'NVIDIA GeForce RTX 4070',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '12GB GDDR6X',
        memoryBus: '192-bit',
        cudaCores: 5888,
        baseClock: '1.92 GHz',
        boostClock: '2.48 GHz',
        tdp: 200,
        msrp: 549,
        releaseYear: 2023,
        performance: 'Good 1440p gaming. Excellent efficiency.',
        goodFor: ['1440p gaming', '1080p high refresh'],
        psuRecommendation: '650W minimum',
        competitors: ['RX 7700 XT', 'RTX 4060 Ti'],
    },
    'rtx 4060 ti': {
        name: 'NVIDIA GeForce RTX 4060 Ti',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '8GB/16GB GDDR6',
        memoryBus: '128-bit',
        cudaCores: 4352,
        baseClock: '2.31 GHz',
        boostClock: '2.54 GHz',
        tdp: 160,
        msrp: 399,
        releaseYear: 2023,
        performance: '1080p Ultra champion. Decent 1440p.',
        goodFor: ['1080p Ultra', '1440p Medium-High'],
        psuRecommendation: '550W minimum',
        competitors: ['RX 7600 XT', 'RTX 4060'],
    },
    'rtx 4060': {
        name: 'NVIDIA GeForce RTX 4060',
        type: 'GPU',
        architecture: 'Ada Lovelace',
        vram: '8GB GDDR6',
        memoryBus: '128-bit',
        cudaCores: 3072,
        baseClock: '1.83 GHz',
        boostClock: '2.46 GHz',
        tdp: 115,
        msrp: 299,
        releaseYear: 2023,
        performance: 'Budget 1080p gaming with DLSS 3.',
        goodFor: ['1080p gaming', 'Budget builds'],
        psuRecommendation: '500W minimum',
        competitors: ['RX 7600', 'RTX 3060'],
    },
    // RTX 30 Series (still relevant)
    'rtx 3090': {
        name: 'NVIDIA GeForce RTX 3090',
        type: 'GPU',
        architecture: 'Ampere',
        vram: '24GB GDDR6X',
        memoryBus: '384-bit',
        cudaCores: 10496,
        baseClock: '1.40 GHz',
        boostClock: '1.70 GHz',
        tdp: 350,
        msrp: 1499,
        releaseYear: 2020,
        performance: 'Previous gen flagship. Still great for 4K and AI workloads.',
        goodFor: ['4K gaming', 'Machine learning', '3D rendering'],
        psuRecommendation: '750W minimum',
        competitors: ['RTX 4080', 'RTX 3090 Ti'],
    },
    'rtx 3080': {
        name: 'NVIDIA GeForce RTX 3080',
        type: 'GPU',
        architecture: 'Ampere',
        vram: '10GB/12GB GDDR6X',
        memoryBus: '320-bit',
        cudaCores: 8704,
        baseClock: '1.44 GHz',
        boostClock: '1.71 GHz',
        tdp: 320,
        msrp: 699,
        releaseYear: 2020,
        performance: 'Great used market value. Solid 4K gaming.',
        goodFor: ['4K gaming', '1440p high refresh'],
        psuRecommendation: '750W minimum',
        competitors: ['RTX 4070', 'RX 6800 XT'],
    },
    'rtx 3070': {
        name: 'NVIDIA GeForce RTX 3070',
        type: 'GPU',
        architecture: 'Ampere',
        vram: '8GB GDDR6',
        memoryBus: '256-bit',
        cudaCores: 5888,
        baseClock: '1.50 GHz',
        boostClock: '1.73 GHz',
        tdp: 220,
        msrp: 499,
        releaseYear: 2020,
        performance: 'Good 1440p gaming. Still holds up.',
        goodFor: ['1440p gaming', '1080p high refresh'],
        psuRecommendation: '650W minimum',
        competitors: ['RTX 4060 Ti', 'RX 6800'],
    },
    'rtx 3060': {
        name: 'NVIDIA GeForce RTX 3060',
        type: 'GPU',
        architecture: 'Ampere',
        vram: '12GB GDDR6',
        memoryBus: '192-bit',
        cudaCores: 3584,
        baseClock: '1.32 GHz',
        boostClock: '1.78 GHz',
        tdp: 170,
        msrp: 329,
        releaseYear: 2021,
        performance: 'Budget 1080p card with good VRAM.',
        goodFor: ['1080p gaming', 'Budget builds'],
        psuRecommendation: '550W minimum',
        competitors: ['RTX 4060', 'RX 6700 XT'],
    },
    // GTX Series
    'gtx 1660 super': {
        name: 'NVIDIA GeForce GTX 1660 Super',
        type: 'GPU',
        architecture: 'Turing',
        vram: '6GB GDDR6',
        memoryBus: '192-bit',
        cudaCores: 1408,
        baseClock: '1.53 GHz',
        boostClock: '1.79 GHz',
        tdp: 125,
        msrp: 229,
        releaseYear: 2019,
        performance: 'Budget 1080p gaming. No ray tracing.',
        goodFor: ['1080p gaming', 'Esports'],
        psuRecommendation: '450W minimum',
        competitors: ['RX 6500 XT', 'GTX 1650 Super'],
    },
    'gtx 1080 ti': {
        name: 'NVIDIA GeForce GTX 1080 Ti',
        type: 'GPU',
        architecture: 'Pascal',
        vram: '11GB GDDR5X',
        memoryBus: '352-bit',
        cudaCores: 3584,
        baseClock: '1.48 GHz',
        boostClock: '1.58 GHz',
        tdp: 250,
        msrp: 699,
        releaseYear: 2017,
        performance: 'Legendary GPU. Still decent for 1080p/1440p.',
        goodFor: ['1080p gaming', '1440p medium'],
        psuRecommendation: '600W minimum',
        competitors: ['RTX 2070 Super', 'RX 5700 XT'],
    },
};

// --- NVIDIA PROFESSIONAL/WORKSTATION GPUs ---
export const NVIDIA_WORKSTATION_GPUS = {
    'quadro m4000': {
        name: 'NVIDIA Quadro M4000',
        type: 'GPU (Workstation)',
        architecture: 'Maxwell',
        vram: '8GB GDDR5',
        memoryBus: '256-bit',
        cudaCores: 1664,
        baseClock: '773 MHz',
        boostClock: '842 MHz',
        tdp: 120,
        msrp: 845,
        releaseYear: 2015,
        performance: 'Professional workstation card for CAD, 3D modeling, and visualization.',
        goodFor: ['AutoCAD', 'SolidWorks', 'Maya', '3ds Max', 'Revit', 'Professional 3D applications'],
        applications: ['CAD/CAM', '3D modeling', 'Video editing', 'Medical imaging'],
        driverSupport: 'Quadro drivers (professional certified)',
        displayOutputs: '4x DisplayPort 1.2',
        notes: 'Older workstation card. For gaming, consumer GPUs are better. For professional work with certified drivers, Quadro line still relevant.',
        psuRecommendation: '450W minimum',
        competitors: ['Quadro P4000', 'AMD FirePro W7100'],
        isWorkstation: true,
    },
    'quadro p4000': {
        name: 'NVIDIA Quadro P4000',
        type: 'GPU (Workstation)',
        architecture: 'Pascal',
        vram: '8GB GDDR5',
        memoryBus: '256-bit',
        cudaCores: 1792,
        baseClock: '1.22 GHz',
        boostClock: '1.48 GHz',
        tdp: 105,
        msrp: 799,
        releaseYear: 2017,
        performance: 'Mid-range workstation card. Successor to M4000.',
        goodFor: ['CAD', '3D modeling', 'Video editing', 'Professional visualization'],
        applications: ['AutoCAD', 'SolidWorks', 'Revit', 'DaVinci Resolve'],
        driverSupport: 'Quadro drivers (ISV certified)',
        displayOutputs: '4x DisplayPort 1.4',
        psuRecommendation: '450W minimum',
        competitors: ['Quadro M4000', 'AMD Radeon Pro WX 7100'],
        isWorkstation: true,
    },
    'quadro rtx 4000': {
        name: 'NVIDIA Quadro RTX 4000',
        type: 'GPU (Workstation)',
        architecture: 'Turing',
        vram: '8GB GDDR6',
        memoryBus: '256-bit',
        cudaCores: 2304,
        rtCores: 36,
        tensorCores: 288,
        baseClock: '1.00 GHz',
        boostClock: '1.55 GHz',
        tdp: 160,
        msrp: 899,
        releaseYear: 2018,
        performance: 'Ray tracing workstation card for professional visualization.',
        goodFor: ['Real-time ray tracing', 'VR development', 'CAD', '3D rendering'],
        applications: ['Blender', 'Unreal Engine', 'AutoCAD', 'SolidWorks'],
        driverSupport: 'Quadro RTX drivers',
        displayOutputs: '3x DisplayPort 1.4, 1x VirtualLink',
        psuRecommendation: '500W minimum',
        competitors: ['RTX A4000', 'AMD Radeon Pro W5700'],
        isWorkstation: true,
    },
    'rtx a4000': {
        name: 'NVIDIA RTX A4000',
        type: 'GPU (Workstation)',
        architecture: 'Ampere',
        vram: '16GB GDDR6',
        memoryBus: '256-bit',
        cudaCores: 6144,
        rtCores: 48,
        tensorCores: 192,
        baseClock: '735 MHz',
        boostClock: '1.56 GHz',
        tdp: 140,
        msrp: 1000,
        releaseYear: 2021,
        performance: 'Modern workstation GPU with AI acceleration.',
        goodFor: ['CAD', 'AI/ML', '3D rendering', 'Video editing', 'VR development'],
        applications: ['SolidWorks', 'AutoCAD', 'Blender', 'DaVinci Resolve', 'Unreal Engine'],
        driverSupport: 'NVIDIA RTX Enterprise drivers',
        displayOutputs: '4x DisplayPort 1.4a',
        psuRecommendation: '500W minimum',
        competitors: ['Quadro RTX 4000', 'AMD Radeon Pro W6800'],
        isWorkstation: true,
    },
    'rtx a6000': {
        name: 'NVIDIA RTX A6000',
        type: 'GPU (Workstation)',
        architecture: 'Ampere',
        vram: '48GB GDDR6',
        memoryBus: '384-bit',
        cudaCores: 10752,
        rtCores: 84,
        tensorCores: 336,
        baseClock: '1.41 GHz',
        boostClock: '1.80 GHz',
        tdp: 300,
        msrp: 4650,
        releaseYear: 2020,
        performance: 'Top-tier workstation GPU for demanding professional workloads.',
        goodFor: ['AI/ML training', 'Film production', 'Scientific visualization', '8K editing'],
        applications: ['Data science', 'Deep learning', 'VFX', 'Simulation'],
        driverSupport: 'NVIDIA RTX Enterprise drivers',
        displayOutputs: '4x DisplayPort 1.4a',
        psuRecommendation: '650W minimum',
        competitors: ['AMD Radeon Pro W6900X'],
        isWorkstation: true,
    },
};

// --- AMD CONSUMER GPUs ---
export const AMD_CONSUMER_GPUS = {
    'rx 7900 xtx': {
        name: 'AMD Radeon RX 7900 XTX',
        type: 'GPU',
        architecture: 'RDNA 3',
        vram: '24GB GDDR6',
        memoryBus: '384-bit',
        streamProcessors: 6144,
        baseClock: '1.90 GHz',
        boostClock: '2.50 GHz',
        tdp: 355,
        msrp: 999,
        releaseYear: 2022,
        performance: 'AMD flagship. Competes with RTX 4080.',
        goodFor: ['4K gaming', '1440p high refresh', 'Content creation'],
        psuRecommendation: '800W minimum',
        competitors: ['RTX 4080', 'RTX 4080 Super'],
    },
    'rx 7900 xt': {
        name: 'AMD Radeon RX 7900 XT',
        type: 'GPU',
        architecture: 'RDNA 3',
        vram: '20GB GDDR6',
        memoryBus: '320-bit',
        streamProcessors: 5376,
        baseClock: '1.50 GHz',
        boostClock: '2.40 GHz',
        tdp: 315,
        msrp: 799,
        releaseYear: 2022,
        performance: 'Great 4K value. Lots of VRAM.',
        goodFor: ['4K gaming', '1440p', 'High VRAM workloads'],
        psuRecommendation: '750W minimum',
        competitors: ['RTX 4070 Ti Super', 'RTX 4080'],
    },
    'rx 7800 xt': {
        name: 'AMD Radeon RX 7800 XT',
        type: 'GPU',
        architecture: 'RDNA 3',
        vram: '16GB GDDR6',
        memoryBus: '256-bit',
        streamProcessors: 3840,
        baseClock: '1.30 GHz',
        boostClock: '2.43 GHz',
        tdp: 263,
        msrp: 499,
        releaseYear: 2023,
        performance: 'Best value 1440p GPU. Great VRAM.',
        goodFor: ['1440p gaming', 'High texture games', 'Longevity'],
        psuRecommendation: '650W minimum',
        competitors: ['RTX 4070', 'RTX 4070 Super'],
    },
    'rx 7700 xt': {
        name: 'AMD Radeon RX 7700 XT',
        type: 'GPU',
        architecture: 'RDNA 3',
        vram: '12GB GDDR6',
        memoryBus: '192-bit',
        streamProcessors: 3456,
        baseClock: '1.70 GHz',
        boostClock: '2.54 GHz',
        tdp: 245,
        msrp: 449,
        releaseYear: 2023,
        performance: 'Solid 1440p performance.',
        goodFor: ['1440p gaming', '1080p high refresh'],
        psuRecommendation: '600W minimum',
        competitors: ['RTX 4060 Ti', 'RTX 4070'],
    },
    'rx 7600': {
        name: 'AMD Radeon RX 7600',
        type: 'GPU',
        architecture: 'RDNA 3',
        vram: '8GB GDDR6',
        memoryBus: '128-bit',
        streamProcessors: 2048,
        baseClock: '1.72 GHz',
        boostClock: '2.66 GHz',
        tdp: 165,
        msrp: 269,
        releaseYear: 2023,
        performance: 'Budget 1080p with modern architecture.',
        goodFor: ['1080p gaming', 'Budget builds'],
        psuRecommendation: '550W minimum',
        competitors: ['RTX 4060', 'RX 6700 XT'],
    },
    'rx 6800 xt': {
        name: 'AMD Radeon RX 6800 XT',
        type: 'GPU',
        architecture: 'RDNA 2',
        vram: '16GB GDDR6',
        memoryBus: '256-bit',
        streamProcessors: 4608,
        baseClock: '1.83 GHz',
        boostClock: '2.25 GHz',
        tdp: 300,
        msrp: 649,
        releaseYear: 2020,
        performance: 'Great used market value. Solid 4K.',
        goodFor: ['1440p gaming', '4K medium'],
        psuRecommendation: '700W minimum',
        competitors: ['RTX 3080', 'RTX 4070'],
    },
    'rx 6700 xt': {
        name: 'AMD Radeon RX 6700 XT',
        type: 'GPU',
        architecture: 'RDNA 2',
        vram: '12GB GDDR6',
        memoryBus: '192-bit',
        streamProcessors: 2560,
        baseClock: '2.32 GHz',
        boostClock: '2.58 GHz',
        tdp: 230,
        msrp: 479,
        releaseYear: 2021,
        performance: 'Good 1440p gaming.',
        goodFor: ['1440p gaming', '1080p high refresh'],
        psuRecommendation: '600W minimum',
        competitors: ['RTX 3060 Ti', 'RTX 4060'],
    },
    'rx 6650 xt': {
        name: 'AMD Radeon RX 6650 XT',
        type: 'GPU',
        architecture: 'RDNA 2',
        vram: '8GB GDDR6',
        memoryBus: '128-bit',
        streamProcessors: 2048,
        baseClock: '2.06 GHz',
        boostClock: '2.64 GHz',
        tdp: 180,
        msrp: 239,
        releaseYear: 2022,
        performance: 'Budget 1080p powerhouse.',
        goodFor: ['1080p gaming', 'Esports'],
        psuRecommendation: '500W minimum',
        competitors: ['RTX 3060', 'GTX 1660 Super'],
    },
};

// --- INTEL CPUs ---
export const INTEL_CPUS = {
    'i9-14900k': {
        name: 'Intel Core i9-14900K',
        type: 'CPU',
        architecture: 'Raptor Lake Refresh',
        cores: 24,
        threads: 32,
        pCores: 8,
        eCores: 16,
        baseClock: '3.2 GHz',
        boostClock: '6.0 GHz',
        cache: '36MB L3',
        tdp: 125,
        maxTurboTdp: 253,
        socket: 'LGA 1700',
        msrp: 589,
        releaseYear: 2023,
        performance: 'Intel flagship. Best multi-threaded performance.',
        goodFor: ['Content creation', 'Streaming', 'Multi-tasking', 'Gaming'],
        coolerRecommendation: '360mm AIO or high-end air cooler',
        ramSupport: 'DDR4-3200 / DDR5-5600',
        competitors: ['Ryzen 9 7950X', 'i9-13900K'],
    },
    'i7-14700k': {
        name: 'Intel Core i7-14700K',
        type: 'CPU',
        architecture: 'Raptor Lake Refresh',
        cores: 20,
        threads: 28,
        pCores: 8,
        eCores: 12,
        baseClock: '3.4 GHz',
        boostClock: '5.6 GHz',
        cache: '33MB L3',
        tdp: 125,
        maxTurboTdp: 253,
        socket: 'LGA 1700',
        msrp: 409,
        releaseYear: 2023,
        performance: 'Excellent productivity CPU with good gaming.',
        goodFor: ['Content creation', 'Gaming', 'Streaming', 'Workstation'],
        coolerRecommendation: '280mm+ AIO or tower cooler',
        ramSupport: 'DDR4-3200 / DDR5-5600',
        competitors: ['Ryzen 7 7800X3D', 'Ryzen 9 7900X'],
    },
    'i5-14600k': {
        name: 'Intel Core i5-14600K',
        type: 'CPU',
        architecture: 'Raptor Lake Refresh',
        cores: 14,
        threads: 20,
        pCores: 6,
        eCores: 8,
        baseClock: '3.5 GHz',
        boostClock: '5.3 GHz',
        cache: '24MB L3',
        tdp: 125,
        maxTurboTdp: 181,
        socket: 'LGA 1700',
        msrp: 319,
        releaseYear: 2023,
        performance: 'Best value Intel gaming CPU.',
        goodFor: ['Gaming', 'General productivity', 'Streaming'],
        coolerRecommendation: 'Tower cooler or 240mm AIO',
        ramSupport: 'DDR4-3200 / DDR5-5600',
        competitors: ['Ryzen 5 7600X', 'Ryzen 7 5800X3D'],
    },
    'i5-13400f': {
        name: 'Intel Core i5-13400F',
        type: 'CPU',
        architecture: 'Raptor Lake',
        cores: 10,
        threads: 16,
        pCores: 6,
        eCores: 4,
        baseClock: '2.5 GHz',
        boostClock: '4.6 GHz',
        cache: '20MB L3',
        tdp: 65,
        maxTurboTdp: 148,
        socket: 'LGA 1700',
        msrp: 199,
        releaseYear: 2023,
        performance: 'Budget gaming king. No integrated graphics (F suffix).',
        goodFor: ['Gaming', 'Budget builds', 'General use'],
        coolerRecommendation: 'Stock or budget tower cooler',
        ramSupport: 'DDR4-3200 / DDR5-4800',
        competitors: ['Ryzen 5 7600', 'Ryzen 5 5600'],
    },
    'i3-12100f': {
        name: 'Intel Core i3-12100F',
        type: 'CPU',
        architecture: 'Alder Lake',
        cores: 4,
        threads: 8,
        pCores: 4,
        eCores: 0,
        baseClock: '3.3 GHz',
        boostClock: '4.3 GHz',
        cache: '12MB L3',
        tdp: 58,
        socket: 'LGA 1700',
        msrp: 99,
        releaseYear: 2022,
        performance: 'Incredible budget value. Solid 1080p gaming.',
        goodFor: ['Budget gaming', 'Office work', 'Esports'],
        coolerRecommendation: 'Stock cooler included',
        ramSupport: 'DDR4-3200 / DDR5-4800',
        competitors: ['Ryzen 3 4100', 'Ryzen 5 5500'],
    },
};

// --- AMD CPUs ---
export const AMD_CPUS = {
    'ryzen 9 7950x': {
        name: 'AMD Ryzen 9 7950X',
        type: 'CPU',
        architecture: 'Zen 4',
        cores: 16,
        threads: 32,
        baseClock: '4.5 GHz',
        boostClock: '5.7 GHz',
        cache: '64MB L3',
        tdp: 170,
        socket: 'AM5',
        msrp: 549,
        releaseYear: 2022,
        performance: 'AMD flagship. Massive multi-threaded power.',
        goodFor: ['Content creation', '3D rendering', 'Streaming', 'Gaming'],
        coolerRecommendation: '360mm AIO',
        ramSupport: 'DDR5-5200',
        competitors: ['i9-14900K', 'Ryzen 9 7950X3D'],
    },
    'ryzen 9 7950x3d': {
        name: 'AMD Ryzen 9 7950X3D',
        type: 'CPU',
        architecture: 'Zen 4 + 3D V-Cache',
        cores: 16,
        threads: 32,
        baseClock: '4.2 GHz',
        boostClock: '5.7 GHz',
        cache: '128MB L3 (3D V-Cache)',
        tdp: 120,
        socket: 'AM5',
        msrp: 699,
        releaseYear: 2023,
        performance: 'Best of both worlds: gaming + productivity.',
        goodFor: ['Hybrid workloads', 'Gaming', 'Streaming', 'Content creation'],
        coolerRecommendation: '280mm+ AIO',
        ramSupport: 'DDR5-5200',
        competitors: ['i9-14900K', 'Ryzen 7 7800X3D'],
    },
    'ryzen 7 7800x3d': {
        name: 'AMD Ryzen 7 7800X3D',
        type: 'CPU',
        architecture: 'Zen 4 + 3D V-Cache',
        cores: 8,
        threads: 16,
        baseClock: '4.2 GHz',
        boostClock: '5.0 GHz',
        cache: '96MB L3 (3D V-Cache)',
        tdp: 120,
        socket: 'AM5',
        msrp: 449,
        releaseYear: 2023,
        performance: 'THE BEST gaming CPU. 3D V-Cache gives 10-20% extra FPS.',
        goodFor: ['Gaming (absolute best)', 'High refresh gaming', 'Esports'],
        coolerRecommendation: 'Tower cooler or 240mm AIO',
        ramSupport: 'DDR5-5200',
        competitors: ['i5-14600K', 'i7-14700K'],
    },
    'ryzen 7 7700x': {
        name: 'AMD Ryzen 7 7700X',
        type: 'CPU',
        architecture: 'Zen 4',
        cores: 8,
        threads: 16,
        baseClock: '4.5 GHz',
        boostClock: '5.4 GHz',
        cache: '32MB L3',
        tdp: 105,
        socket: 'AM5',
        msrp: 349,
        releaseYear: 2022,
        performance: 'Great all-around CPU for gaming and productivity.',
        goodFor: ['Gaming', 'Productivity', 'Streaming'],
        coolerRecommendation: 'Tower cooler',
        ramSupport: 'DDR5-5200',
        competitors: ['i7-13700K', 'i5-14600K'],
    },
    'ryzen 5 7600': {
        name: 'AMD Ryzen 5 7600',
        type: 'CPU',
        architecture: 'Zen 4',
        cores: 6,
        threads: 12,
        baseClock: '3.8 GHz',
        boostClock: '5.1 GHz',
        cache: '32MB L3',
        tdp: 65,
        socket: 'AM5',
        msrp: 199,
        releaseYear: 2023,
        performance: 'Best value AM5 CPU. Comes with cooler.',
        goodFor: ['Gaming', 'Budget builds', 'General use'],
        coolerRecommendation: 'Stock cooler included',
        ramSupport: 'DDR5-5200',
        competitors: ['i5-13400F', 'Ryzen 5 5600'],
    },
    'ryzen 5 5600': {
        name: 'AMD Ryzen 5 5600',
        type: 'CPU',
        architecture: 'Zen 3',
        cores: 6,
        threads: 12,
        baseClock: '3.5 GHz',
        boostClock: '4.4 GHz',
        cache: '32MB L3',
        tdp: 65,
        socket: 'AM4',
        msrp: 129,
        releaseYear: 2022,
        performance: 'Best budget CPU. AM4 platform is cheap.',
        goodFor: ['Budget gaming', 'General use', 'Upgrades'],
        coolerRecommendation: 'Stock cooler included',
        ramSupport: 'DDR4-3200',
        competitors: ['i3-12100F', 'Ryzen 5 5500'],
    },
    'ryzen 5 5600x': {
        name: 'AMD Ryzen 5 5600X',
        type: 'CPU',
        architecture: 'Zen 3',
        cores: 6,
        threads: 12,
        baseClock: '3.7 GHz',
        boostClock: '4.6 GHz',
        cache: '32MB L3',
        tdp: 65,
        socket: 'AM4',
        msrp: 199,
        releaseYear: 2020,
        performance: 'Legendary value CPU. Still great in 2024.',
        goodFor: ['Gaming', 'Productivity', 'Budget builds'],
        coolerRecommendation: 'Stock cooler included',
        ramSupport: 'DDR4-3200',
        competitors: ['i5-12400F', 'Ryzen 5 5600'],
    },
    'ryzen 7 5800x3d': {
        name: 'AMD Ryzen 7 5800X3D',
        type: 'CPU',
        architecture: 'Zen 3 + 3D V-Cache',
        cores: 8,
        threads: 16,
        baseClock: '3.4 GHz',
        boostClock: '4.5 GHz',
        cache: '96MB L3 (3D V-Cache)',
        tdp: 105,
        socket: 'AM4',
        msrp: 329,
        releaseYear: 2022,
        performance: 'Best gaming CPU for AM4. Great upgrade path.',
        goodFor: ['Gaming', 'AM4 upgrades'],
        coolerRecommendation: 'Tower cooler',
        ramSupport: 'DDR4-3200',
        competitors: ['Ryzen 7 7800X3D', 'i5-14600K'],
    },
};

// --- MOTHERBOARD CHIPSETS ---
export const MOTHERBOARD_CHIPSETS = {
    // Intel
    'z790': {
        name: 'Intel Z790',
        platform: 'Intel 12th/13th/14th Gen',
        socket: 'LGA 1700',
        overclockSupport: true,
        pcieLanes: '20 (CPU) + 28 (Chipset)',
        memorySupport: 'DDR4 or DDR5',
        features: 'Full overclocking, maximum expansion',
        priceRange: '$200-600',
        goodFor: 'Enthusiasts, overclockers, high-end builds',
    },
    'b760': {
        name: 'Intel B760',
        platform: 'Intel 12th/13th/14th Gen',
        socket: 'LGA 1700',
        overclockSupport: false,
        pcieLanes: '20 (CPU) + 14 (Chipset)',
        memorySupport: 'DDR4 or DDR5',
        features: 'Memory OC, good value',
        priceRange: '$100-200',
        goodFor: 'Most users, gaming builds',
    },
    'h770': {
        name: 'Intel H770',
        platform: 'Intel 12th/13th/14th Gen',
        socket: 'LGA 1700',
        overclockSupport: false,
        pcieLanes: '20 (CPU) + 24 (Chipset)',
        memorySupport: 'DDR4 or DDR5',
        features: 'More I/O than B760',
        priceRange: '$150-250',
        goodFor: 'Workstations, content creators',
    },
    // AMD
    'x670e': {
        name: 'AMD X670E',
        platform: 'AMD Ryzen 7000 Series',
        socket: 'AM5',
        overclockSupport: true,
        pcieLanes: 'PCIe 5.0 for GPU + Storage',
        memorySupport: 'DDR5 only',
        features: 'Full PCIe 5.0, maximum expansion',
        priceRange: '$300-700',
        goodFor: 'Enthusiasts, future-proofing',
    },
    'x670': {
        name: 'AMD X670',
        platform: 'AMD Ryzen 7000 Series',
        socket: 'AM5',
        overclockSupport: true,
        pcieLanes: 'PCIe 5.0 optional',
        memorySupport: 'DDR5 only',
        features: 'Overclocking, good expansion',
        priceRange: '$250-450',
        goodFor: 'Enthusiasts, high-end builds',
    },
    'b650e': {
        name: 'AMD B650E',
        platform: 'AMD Ryzen 7000 Series',
        socket: 'AM5',
        overclockSupport: true,
        pcieLanes: 'PCIe 5.0 for GPU',
        memorySupport: 'DDR5 only',
        features: 'PCIe 5.0 GPU slot, value',
        priceRange: '$180-300',
        goodFor: 'Most users wanting PCIe 5.0',
    },
    'b650': {
        name: 'AMD B650',
        platform: 'AMD Ryzen 7000 Series',
        socket: 'AM5',
        overclockSupport: true,
        pcieLanes: 'PCIe 4.0',
        memorySupport: 'DDR5 only',
        features: 'Best value for AM5',
        priceRange: '$130-220',
        goodFor: 'Most AM5 builds, gaming',
    },
    'b550': {
        name: 'AMD B550',
        platform: 'AMD Ryzen 3000/5000 Series',
        socket: 'AM4',
        overclockSupport: true,
        pcieLanes: 'PCIe 4.0 (primary)',
        memorySupport: 'DDR4',
        features: 'Best value AM4',
        priceRange: '$80-180',
        goodFor: 'Budget builds with Ryzen 5000',
    },
    'x570': {
        name: 'AMD X570',
        platform: 'AMD Ryzen 3000/5000 Series',
        socket: 'AM4',
        overclockSupport: true,
        pcieLanes: 'Full PCIe 4.0',
        memorySupport: 'DDR4',
        features: 'Maximum AM4 expansion',
        priceRange: '$150-400',
        goodFor: 'High-end AM4, content creation',
    },
};

// --- RAM ---
export const RAM_SPECS = {
    'ddr5': {
        name: 'DDR5',
        type: 'RAM',
        speedRange: '4800-8000+ MHz',
        typicalCapacity: '32GB (2x16GB)',
        voltageRange: '1.1-1.4V',
        priceRange: '$100-400',
        goodFor: 'New builds (AM5, LGA1700), future-proofing',
        notes: 'Higher bandwidth, on-die ECC, better for productivity. Gaming sees minimal difference vs DDR4.',
    },
    'ddr4': {
        name: 'DDR4',
        type: 'RAM',
        speedRange: '2133-4800 MHz',
        typicalCapacity: '32GB (2x16GB)',
        voltageRange: '1.2-1.5V',
        priceRange: '$50-150',
        goodFor: 'AM4 builds, budget builds, mature platform',
        notes: 'Still excellent. Sweet spot is 3200-3600MHz for AMD, 3200MHz for Intel.',
    },
};

// --- STORAGE ---
export const STORAGE_TYPES = {
    'nvme gen5': {
        name: 'NVMe Gen 5 SSD',
        type: 'Storage',
        interface: 'PCIe 5.0 x4',
        maxSpeed: '12,000+ MB/s',
        typicalCapacity: '1-4TB',
        priceRange: '$150-800',
        goodFor: 'Content creation, large file transfers',
        notes: 'Overkill for gaming. Runs hot, needs heatsink.',
    },
    'nvme gen4': {
        name: 'NVMe Gen 4 SSD',
        type: 'Storage',
        interface: 'PCIe 4.0 x4',
        maxSpeed: '7,000 MB/s',
        typicalCapacity: '500GB-4TB',
        priceRange: '$50-400',
        goodFor: 'Gaming, general use, content creation',
        notes: 'Best value for performance. Sweet spot is 1-2TB.',
    },
    'nvme gen3': {
        name: 'NVMe Gen 3 SSD',
        type: 'Storage',
        interface: 'PCIe 3.0 x4',
        maxSpeed: '3,500 MB/s',
        typicalCapacity: '250GB-2TB',
        priceRange: '$30-200',
        goodFor: 'Budget builds, secondary storage',
        notes: 'Still fast for most users. Great budget option.',
    },
    'sata ssd': {
        name: 'SATA SSD',
        type: 'Storage',
        interface: 'SATA III',
        maxSpeed: '550 MB/s',
        typicalCapacity: '250GB-4TB',
        priceRange: '$20-300',
        goodFor: 'Mass storage, old systems, budget',
        notes: 'Much slower than NVMe but still vastly better than HDD.',
    },
    'hdd': {
        name: 'Hard Disk Drive (HDD)',
        type: 'Storage',
        interface: 'SATA III',
        maxSpeed: '150-200 MB/s',
        typicalCapacity: '1-20TB',
        priceRange: '$30-400',
        goodFor: 'Mass storage, backups, archives',
        notes: 'Slow but cheap per TB. Not recommended as boot drive.',
    },
};

// --- POWER SUPPLIES ---
export const PSU_TIERS = {
    'tier a': {
        name: 'Tier A (Premium)',
        examples: ['Corsair RMx', 'Seasonic Focus GX', 'be quiet! Straight Power', 'EVGA SuperNOVA G6'],
        efficiency: '80+ Gold or better',
        warranty: '7-12 years',
        features: 'Excellent components, quiet, reliable',
        priceRange: '$90-200',
        goodFor: 'High-end builds, longevity',
    },
    'tier b': {
        name: 'Tier B (Good)',
        examples: ['Corsair CX-F', 'MSI A-GF', 'Thermaltake Toughpower GF1'],
        efficiency: '80+ Gold',
        warranty: '5-10 years',
        features: 'Good quality, reliable',
        priceRange: '$60-100',
        goodFor: 'Most gaming builds',
    },
    'tier c': {
        name: 'Tier C (Acceptable)',
        examples: ['EVGA BQ', 'Corsair CXM', 'Thermaltake Smart'],
        efficiency: '80+ Bronze',
        warranty: '3-5 years',
        features: 'Basic quality, budget-friendly',
        priceRange: '$40-70',
        goodFor: 'Budget builds, low-power systems',
    },
};

// Combine all databases for easy lookup
export const ALL_PARTS = {
    ...NVIDIA_CONSUMER_GPUS,
    ...NVIDIA_WORKSTATION_GPUS,
    ...AMD_CONSUMER_GPUS,
    ...INTEL_CPUS,
    ...AMD_CPUS,
    ...MOTHERBOARD_CHIPSETS,
    ...RAM_SPECS,
    ...STORAGE_TYPES,
    ...PSU_TIERS,
};

/**
 * Search the knowledge base for a part
 */
export const searchParts = (query) => {
    const lower = query.toLowerCase().trim();

    // Direct match
    if (ALL_PARTS[lower]) {
        return ALL_PARTS[lower];
    }

    // Fuzzy search - find parts that contain the query
    const matches = [];
    for (const [key, part] of Object.entries(ALL_PARTS)) {
        if (key.includes(lower) || (part.name && part.name.toLowerCase().includes(lower))) {
            matches.push(part);
        }
    }

    return matches.length === 1 ? matches[0] : matches.length > 1 ? matches : null;
};

/**
 * Format part info for display
 */
export const formatPartInfo = (part) => {
    if (!part) return null;

    let response = `## ${part.name}\n\n`;

    if (part.type) response += `**Type:** ${part.type}\n`;
    if (part.architecture) response += `**Architecture:** ${part.architecture}\n`;
    if (part.releaseYear) response += `**Released:** ${part.releaseYear}\n`;
    if (part.msrp) response += `**MSRP:** $${part.msrp}\n`;

    response += '\n### Specifications\n\n';

    // GPU specs
    if (part.vram) response += `- **VRAM:** ${part.vram}\n`;
    if (part.memoryBus) response += `- **Memory Bus:** ${part.memoryBus}\n`;
    if (part.cudaCores) response += `- **CUDA Cores:** ${part.cudaCores.toLocaleString()}\n`;
    if (part.streamProcessors) response += `- **Stream Processors:** ${part.streamProcessors.toLocaleString()}\n`;
    if (part.baseClock) response += `- **Base Clock:** ${part.baseClock}\n`;
    if (part.boostClock) response += `- **Boost Clock:** ${part.boostClock}\n`;
    if (part.tdp) response += `- **TDP:** ${part.tdp}W\n`;

    // CPU specs
    if (part.cores) response += `- **Cores/Threads:** ${part.cores}/${part.threads || part.cores * 2}\n`;
    if (part.cache) response += `- **Cache:** ${part.cache}\n`;
    if (part.socket) response += `- **Socket:** ${part.socket}\n`;

    // Performance and recommendations
    if (part.performance) {
        response += `\n### Performance\n${part.performance}\n`;
    }

    if (part.goodFor && part.goodFor.length > 0) {
        response += `\n### Best For\n`;
        part.goodFor.forEach(use => {
            response += `- ${use}\n`;
        });
    }

    if (part.applications && part.applications.length > 0) {
        response += `\n### Applications\n`;
        part.applications.forEach(app => {
            response += `- ${app}\n`;
        });
    }

    if (part.psuRecommendation) {
        response += `\n### Power Requirements\n**PSU Recommendation:** ${part.psuRecommendation}\n`;
    }

    if (part.coolerRecommendation) {
        response += `\n### Cooling\n**Recommended Cooler:** ${part.coolerRecommendation}\n`;
    }

    if (part.notes) {
        response += `\n### Notes\n${part.notes}\n`;
    }

    if (part.competitors && part.competitors.length > 0) {
        response += `\n### Competitors\n`;
        part.competitors.forEach(comp => {
            response += `- ${comp}\n`;
        });
    }

    return response;
};

export default {
    ALL_PARTS,
    searchParts,
    formatPartInfo,
    NVIDIA_CONSUMER_GPUS,
    NVIDIA_WORKSTATION_GPUS,
    AMD_CONSUMER_GPUS,
    INTEL_CPUS,
    AMD_CPUS,
    MOTHERBOARD_CHIPSETS,
    RAM_SPECS,
    STORAGE_TYPES,
    PSU_TIERS,
};
